### ISSUE TITLE
Support for Xamarin Native

### ISSUE THREAD

**Issue by bartlannoeye** [microsoft/TemplateStudio#1311]
## For new Features:

* **Overview:** Support for Xamarin.Forms (see Xamarin branch) is great and a nice step up for us Windows developers to go cross platform.
 
As discussed during our user group talk on Windows Template Studio, a lot of firms (at least in Belgium) doing Xamarin started in the early days. Most of them are still doing Xamarin native for all 3 platforms. I got an actual request from one of these firms after showing what WTS can do if this 'awesome tool' would be available for Xamarin native as well as they're not looking into moving to Xamarin.Forms yet (since they have all the skillsets in house).

**Comment by mikebattista** [comment]
Closing out this stale issue. Any potential future investment here would be in MAUI.
