### ISSUE TITLE
Right click on Xamarin Forms projects

### ISSUE THREAD

**Issue by sibille** [microsoft/TemplateStudio#1350]
Right click on UWP projects is working with data from the package.appxmanifest.
This information is used to identify if the project was created with WTS, its projectType and framework. 

- [ ] Define where to store project info in xamarin forms projects. 
- [ ] Define from where the rightclick will be available (solution, shared project, android, iOs, Uwp project??)
- [ ] Read project config for xamarin forms
- [ ] Infer project config for xamarin forms

**Comment by mikebattista** [comment]
Closing out this stale issue. Any potential future investment here would be in MAUI.
