### ISSUE TITLE
Create initial xamarin project template (blank)

### ISSUE THREAD

**Issue by ralarcon** [microsoft/TemplateStudio#1441]
Include a project template for xamaring generation in order to validate the generation engine and look for product team feedback.

Include the blank project type.
Requires an small navigation service.

Ensure product team feedback.

**Comment by mrlacey** [comment]
why is this still open? Please close if the work has been done and merged to dev branch or add details of what is still required.

**Comment by mikebattista** [comment]
Closing out this stale issue. Any potential future investment here would be in MAUI.
