### ISSUE TITLE
Adapt FakeSolution and FakeMsBuild to support Xamarin projects

### ISSUE THREAD

**Issue by sibille** [microsoft/TemplateStudio#1471]
- [ ] Add project configurations to FakeSolution
- [ ] Add XAML as embedded items in shared project

**Comment by mrlacey** [comment]
why is this still open? Please close if the work has been done and merged to dev branch or add details of what is still required.

**Comment by mikebattista** [comment]
Closing out this stale issue. Any potential future investment here would be in MAUI.
