### ISSUE TITLE
Step by step guide for template authoring

### ISSUE THREAD

**Issue by ralarcon** [microsoft/TemplateStudio#203]
Now we have a comprehensive [doc for Templates](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/templates.md) but we need to think in having a step by step guide to show how to author templates.

An scenario would showcase how to progresively create a template set (project template, page templates, feature templates...) and the advance features (composition and post-actions) using an accumulative approach. 

Consider that the samples templates created for the step by step guide should be loaded within the VsEmulator test app (i.e. implementing a new SampleTemplateLocation) as well as that the user might want to start in a certain step.

Draft steps:
Step 1: Create a basic project template
Step 2: Create a basic page tamplate
Step 3: Create a basic feature template
Step 4: Understanding composition
Step 5: Understanding merge post-actions
Step 6: Adding pages to the Template repository
Step 7: Adding features to the Template repository
...

**Comment by mrlacey** [comment]
Going forward this could be very useful.
Please can this be done soon?

**Comment by mikebattista** [comment]
Assigning to myself to track improving the documentation to better enable community contributions.

**Comment by mikebattista** [comment]
We've updated https://github.com/microsoft/TemplateStudio/blob/main/CONTRIBUTING.md to cover the core concepts. Any additional context that's needed should be added there.

A step-by-step guide isn't necessary when you can copy an existing page/feature/etc. that's there and modify for your needs. https://github.com/microsoft/TemplateStudio/blob/main/CONTRIBUTING.md explains the core concepts that you need to be able to modify existing templates and create new ones.
