### ISSUE TITLE
Improve post-generation experience and improve awareness of Right-Click functionality

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#2282]
How can we improve the experience once a project has been generated?

After holding the hand of the developer through the wizard we essentially abandon them once they click 'create'.

- Can we do more to draw attention to the `TODO WTS` comments to make it clear that these are things that the developer should do next?
- Can we use this time to help increase awareness of right-click-add functionality? (Under the assumption that this isn't used as much as it could because of a lack of awareness.)
- Can we provide more information about WTS and provide guidance on where to go for assistance and/or provide feedback?

This could be a page that's opened in VS once the project is generated or something else.
We want to avoid unnecessarily adding extra files to a project but also have the information accessible again in the future.

X-Ref #353 

> MEETING NOTES
> Boosting right click add / info
> *	Page in solution file
>    *	Alternatively sync with Daniel / Unni
>        *	Can we do this with VS overview page?
>        *	Can we inject into the VS overview page?
> *	During first time load to hide unpacking time
> *	Update Github homepage
> *	Topics
>     *	Todo list
>     *	Right Click add
>     *	How to report an issue

Applies to the following platforms:
- [x] UWP
- [x] WPF

**Comment by mrlacey** [comment]
Revisiting this in light of  #3078 
It is the case that when someone first generates an app they do not always know what is expected as the next step or how to enhance the generated code.

I feel it would be useful for people getting started with Windows development or not familiar with what is generated if appropriate information was included with the generated app.

The aim would be to:
- avoid overwhelming anyone presented with a large amount of generated code for the first time.
- increase awareness of the ability to use right-click>add (currently this is [hidden in the documentation](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#public-release-instructions) and unlikely to be found by new users of WTS)
- encourage feedback and continued engagement with people using the tool.


**Describe the solution you'd like**

Include a document with the generated project that is displayed after generation.
This file will include:
- Thanks for using WTS message
- What to do next (start with addressing TODO comments)
- How to add to the generated app (show Right-Click>Add option)
- Where to go for answers to general questions (StackOverflow or answers.microsoft)
- How/where to submit feedback or feature requests for Template Studio.
- Other??

To keep the number of files created as small as possible, I suggest making this an HTML document with images embedded as data URIs.

**Comment by mikebattista** [comment]
We already generate a README.md in the main project which includes a note about TODOs already. We could add additional context and try to open it in the editor on project load. There is a [post action](https://github.com/dotnet/templating/wiki/Post-Action-Registry#open-a-file-in-the-editor) for that, but a couple quick attempts to test that resulted in an exception on project creation.

**Comment by mrlacey** [comment]
It strikes me that a more visible way of making it clear that it's possible to add to a previously generated project is to add an entry in the "New Item" dialog. 

This would avoid the need for developers to need to know that there is a special submenu in the project context menu for adding items via the wizard.

The downside is that the new item option(s) would always be available, even for projects not initially generated by the tool. (My guess is that this is why it wasn't done previously.)
It would (I assume) be easy to add a check in the new item wizard for an app that can be added to, and if the app can't be identified as one that was previously generated by the wizard we show an appropriate message.

Does anyone else think this option justifies further exploration?

**Comment by mikebattista** [comment]
What about this?

![image](https://user-images.githubusercontent.com/13860912/175437251-2043375f-d763-4844-8f9c-dfb926daef0e.png)

**Comment by mikebattista** [comment]
The edit menu is now using the bottom screenshot above in all extensions. Remaining work is to clean up and launch the README.md on project creation.
