### ISSUE TITLE
Adding in Search box for features

### ISSUE THREAD

**Issue by crutkas** [microsoft/TemplateStudio#282]
with #14 and an increasing amount of items, it would be helpful to help add in a way to search and refine for items

**Comment by mrlacey** [comment]
Need to think about what gets searched.
In personal discussion about this, the idea of tagging items came up so it's possible to, for example, see all templates that are appropriate to LOB apps.

**Comment by jamesmcroft** [comment]
@mrlacey I like the idea of the item tagging feature. 

In terms of feature, would we do it per sub level or one at the top level (i.e. search a feature, search a page, search etc. or search all features, pages etc.) - Does this make sense?

**Comment by crutkas** [comment]
is it us tagging or an end user tagging stuff?

**Comment by mrlacey** [comment]
@jamesmcroft I'd think a single filter on both pages and features would be simpler.
@crutkas I was assuming us adding tags in the template config as a way to filter or search. Adding full support for a user defined folksonomy would be way down my priority list.

**Comment by ralarcon** [comment]
We are working in some design sketches for this feature. Once ready we will share with you for feedback. I think we can combine "search" with "tag filtering" and, yes, the templates metatada are ready for tagging...

**Comment by mrlacey** [comment]
It might be good to share some design ideas before it's implemented

**Comment by ralarcon** [comment]
Yes, we will not start developing until having it discussed!
