### ISSUE TITLE
Enable the creation of Xamarin.Forms apps

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#321]
From #319 
> Is there a plan to also include templates to help kick-start Xamarin and Xamarin.Forms development? Thinking along the same lines, wouldn't it be great to have the ability to create a Xamarin Forms solution, pick which MVVM framework to use, choose between a hamburger menu or a tabs based app, include settings, themes (light-dark), add maps, login page, splash screen etc. Essentially everything that the Template Studio offers for UWP apps.

Please add any specifics about what you'd like to see for Xamarin.Forms below.

https://github.com/Microsoft/WindowsTemplateStudio/wiki/Xamarin

**Comment by crutkas** [comment]
how is this different than #229?

**Comment by mrlacey** [comment]
#229 is to create a solution containing a UWP app project and a library project (PCL or Net Standard) that could then be used in a Xamarin.Forms (or other) project. It doesn't create anything that targets another platform though.
This issue is a request to be able to create a Xamarin.Forms app from the start. The output from this would be a shared library (or PCL) and multiple platform heads (iOS, Android, Windows, & others?) as if doing File>New>Xamarin.Forms. 
This is the request for the ability to do for Xamarin.Forms, what WTS does for UWP.

**Comment by mrlacey** [comment]
It appears something might be happening in this area....https://github.com/Microsoft/WindowsTemplateStudio/tree/xamarin

**Comment by crutkas** [comment]
Added wiki page

**Comment by nguyenthanhliemfc** [comment]
Is it support Xamarin-forms now?

**Comment by crutkas** [comment]
We have multiple aspects of this built out, we are forming a plan of exact execution.  We'll be sharing shortly for feedback

**Comment by nguyenthanhliemfc** [comment]
@crutkas Thank you

**Comment by mrlacey** [comment]
@nguyenthanhliemfc what, specifically, do you want from Xamaring.Forms support? What should (and shouldn't?) it include or enable you to do?

**Comment by LocalJoost** [comment]
I would use this, and this would definitely help us. We now suffer a lot from 'set up costs' and it makes apps too expensive compared to web apps.

**Comment by jesulink2514** [comment]
@mrlacey I think that bring Prism for Xamarin.Forms templates could be a great start point considering that Prism Template Pack already exists. https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismTemplatePack

**Comment by anotherlab** [comment]
I would like to see push notification supported,  When creating a new cross plat app, that's one of the things need platform specific code to get up and running.

How extensible is Windows Template Studio?  I need to cache data on device and needs to be encrypted.  If I wanted to add [LiteDB](https://github.com/mbdavid/LiteDB) support to bring that fucntionality in, can WTS be extended to make that an option?

**Comment by crutkas** [comment]
@anotherlab  what you're proposing are features.  yes those would have to be thought about in terms of how that would work for xamarin and a dev but right now we're really looking for feedback on the actual implementation for the base.

**Comment by crutkas** [comment]
@LocalJoost so you're ok with the hybrid approach we outlined here: https://github.com/Microsoft/WindowsTemplateStudio/wiki/Xamarin-approach

**Comment by crutkas** [comment]
@jesulink2514 prism was one of the frameworks we were going to have for for Xamarin, but right now, we are heavily interested in the hybrid approach model we are proposing: https://github.com/Microsoft/WindowsTemplateStudio/wiki/Xamarin-approach

**Comment by jamesmcroft** [comment]
Would WTS support all of the current features for all platforms? IMO it would be potentially misleading if they weren't all supported. 

Also what about naming. Supporting Xamarin branches outside of just Windows so Windows Template Studio wouldn't be an accurate name for the extension

**Comment by crutkas** [comment]
@jamesmcroft I wouldn't focus on the name.  That will solve itself.

are you talking if we did the hybrid approach, would UWP workflow have more options than a xamarin one, yes that is possible.  The wizard would have to work that into the design.

There are very desktop specific scenarios and features.

**Comment by jamesmcroft** [comment]
@crutkas thinking back on this around Xamarin support, why couldn't this be its own thing that evolves on it's own. Windows Template Studio has this incredible system that backs it for creating these projects from the provided templates which leans well to having separate UI for the different platforms.

I can see possibilities where there are things developers might want/need for UWP but having this application for Xamarin that cannot support it or vice versa.

**Comment by crutkas** [comment]
@jamesmcroft  It can be its own "thing" but at some point, someone has to do the work.  We've had this as a work item for almost a year.  We're proposing a solution that allows us to maximize our current investments and allows for companion iOS and Android applications.  i'm fine with the system's ability to support native as well but UX has to be considered for these scenarios.

If you're proposing that you (or others) are willing to do the work, lets figure out where we can help and let you guys lead the effort :)

**Comment by keithnicholson** [comment]
Did this die on the vine?

**Comment by mikebattista** [comment]
Closing out this stale issue. Any potential future investment here would be in MAUI.

See the updated [roadmap](https://github.com/microsoft/TemplateStudio/blob/dev/docs/roadmap.md) for our latest priorities.
