### ISSUE TITLE
Use Microsoft.Extensions.Configuration once v3.0 is out of preview

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#3213]
Update the **HTTP Data** and **Web API** features to use Microsoft.Extensions.Configuration once version 3.0 is out of preview.

This will allow the use of new functionality in a way that is supported by Microsoft and not reliant on WTS providing the code for equivalent functionality.

**Comment by mrlacey** [comment]
Removing my assignment as unlikely to work on this in the foreseeable future.

**Comment by mikebattista** [comment]
This no longer seems relevant or a priority, and the WinUI templates will be updated to use the latest versions of Microsoft.Extensions.*.
