### ISSUE TITLE
The UWP docs should direct newcomers to WTS

### ISSUE THREAD

**Issue by rgwood** [microsoft/TemplateStudio#3693]
WTS is incredibly useful, thank you! I think it should be mentioned prominently in the official UWP documentation.

I spent a few weeks trying to build a UWP app "the hard way" before discovering WTS. I wish I'd discovered WTS earlier, it would have made it _much_ easier to get started. But WTS is not mentioned in [the official UWP docs](https://docs.microsoft.com/en-us/windows/uwp/develop/) or on [the code samples page](https://developer.microsoft.com/windows/samples), I only found out about it via the recommendation of a friend.

WTS is not just a timesaver when starting an app - it's also one of the best _documentation_ resources I've found for UWP apps and MVVM. It's really useful to see how all the different parts of a UWP app fit together, and also for comparing the different approaches to MVVM.

I'd suggest collaborating with the Docs team to ensure that newcomers to UWP are directed to WTS somehow.

**Comment by mrlacey** [comment]
WinTS is linked from the **Developer Tools** section of the [Downloads and tools for Windows 10](https://developer.microsoft.com/en-us/windows/downloads/) which is one of the pages linked from [the main UWP docs landing page](https://docs.microsoft.com/en-us/windows/uwp/develop/).
As it's not a sample, it's hard to argue for its inclusion on the samples page.

The main landing page is always highly desired "real estate" but not everything that wants can be included there. Lots of people come to UWP development with varying skills, knowledge, and experience and WinTS will not be appropriate for everyone.

It will probably be more effective to [give feedback to the docs team directly](https://docs.microsoft.com/en-us/windows/uwp/develop/#feedback) with your arguments for why WinTS should be included in their documents.

**Comment by rgwood** [comment]
> As it's not a sample, it's hard to argue for its inclusion on the samples page.

I see where you're coming from, but one of WTS's strengths is _generating_ code samples. You pick which features+frameworks you're interested in, then you can see how they would be used in a real-world application. I think WTS fits in perfectly with the stated goal of the samples page (emphasis mine):

> Learn how to build great apps for Windows by experimenting with these samples. **These samples show you how features work and help you jumpstart your own UWP apps.**

I will raise this with the docs team directly, cheers.

**Comment by mrlacey** [comment]
I've also [submitted an update](https://github.com/MicrosoftDocs/windows-uwp/pull/2505) to add WinTS to the **Developer toolkits and libraries** section of the [Design toolkits and samples for Windows apps](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/#developer-toolkits-and-libraries) page.

**Comment by sibille** [comment]
I think we can make a point for being added to the samples page too, Windows Community Toolkit and Win2d are mentioned there too.

**Comment by mrlacey** [comment]
Moving to the backlog milestone as don't know what else to do with this

**Comment by mikebattista** [comment]
Looking for more ways to promote Template Studio is a good goal. Assigning to myself to track.

**Comment by mikebattista** [comment]
Here are all the places I'm working on updating:

- [ ] https://developer.microsoft.com/windows/downloads/
- [ ] https://docs.microsoft.com/windows/apps/design/downloads/
- [ ] https://docs.microsoft.com/windows/apps/desktop/visual-studio-templates
- [ ] https://docs.microsoft.com/windows/apps/get-started/samples
- [ ] The UWP Start Page in VS (#4459)

**Comment by mikebattista** [comment]
All changes have been made. The UWP Start Page in VS fix is targeted for 17.3 Preview 2.

**Comment by rgwood** [comment]
Awesome!
