### ISSUE TITLE
Tentative Roadmap for January 2021 - June 2021 

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/TemplateStudio#4013]
This is a tentative and *optimistic* roadmap that I am leaving for the team to review and provide feedback on. This will **not** be where all our efforts are mapped to, but will be what we prioritize the most while we work on establishing a story for WinUI 3. This roadmap is subject to change and any updates made will be shown here.

![Roadmap for Windows TS January - June 2021](https://user-images.githubusercontent.com/33772802/102309255-fddb0680-3f2d-11eb-93dd-5a216533ee21.png)

**Comment by mrlacey** [comment]
Does this issue replace https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/roadmap.md

**Comment by mrlacey** [comment]
February says start work on the UWP templates for WinUI3, but [in the latest latest community call, UWP support is stated to not be coming until the second half of 2021](https://youtu.be/RGmm341kJMI?t=2495).

**Comment by mrlacey** [comment]
For accessibility, the OP contains an image with this text:

---

**January** - Wrap up WinUI3 C# Desktop and begin work on WinUI3 C++ templates
**February** - Wrap up WinUI3 C++ templates and begin work on WinUI3 UWP templates
**March** - Establish right level of parity with our WinUI3 Desktop and UWP templates
**April** - Code complete for initial set of WinUI3 templates (C++ & C#)
**May** - Expand on C++ templates
**June** - Improvements on currently offered templates and frameworks 👀

**Comment by JeanRoca** [comment]
> Does this issue replace https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/roadmap.md

I would say complements would be the better phrase here. 

> February says start work on the UWP templates for WinUI3, but [in the latest latest community call, UWP support is stated to not be coming until the second half of 2021](https://youtu.be/RGmm341kJMI?t=2495).

The question on the community call was related to .NET 5 support. I believe the current plan is that WinUI will support UWP in a preview state on release.

**Comment by mrlacey** [comment]
> The question on the community call was related to .NET 5 support. I believe the current plan is that WinUI will support UWP in a preview state on release.

The question was vague (about UWP targeting .NET5) but the answer given was specific and surprising.

Ryan Demopolous: "Initially WinUI 3.0 is going to be focused mainly on Win32. We want to add the ability for UWP apps to be able to move to WinUI3 some time after that. I don't know if we have a firm time frame for that but I suspect it will be something along the lines of the back half of next year."

If the WinUI3.0 GA release does fully support existing UWP apps, what will stop them upgrading at GA?

The [feature roadmap for WinUI3](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-30-feature-roadmap) also lists no UWP support until after the 3.0 GA release.

@ryandemopoulos can you clarify/confirm? Will the WinUI3.0 GA release support building and shipping apps using the UWP model?

---

Also "**preview state** on release" is very vague. Is more known about what this preview state will be?
In terms of scheduling, is it worth spending time (a month) on something that will only be in a "preview state" four months later and then released four months after that? It will mean managing, and maintaining something for 8 months before it is released. This is a long time to maintain a separate branch or to keep removing from the main branch when releases are made. Historically, maintaining large numbers of templates prior to release has been a big consumer of time and effort within this project. This has been particularly troublesome when some functionality has been in a pre-release/preview state meaning that not all functionality could be fully tested in an automated way.

**Comment by ryandemopoulos** [comment]
> @ryandemopoulos can you clarify/confirm? Will the WinUI3.0 GA release support building and shipping apps using the UWP model?
> 
> Also "**preview state** on release" is very vague. Is more known about what this preview state will be?

Our current plan for 3.0 GA would carry the following recommendations:

- You can build a production Win32 app using WinUI 3
- WinUI 3.0 GA will work in a UWP context, but in the same way as Preview3 did: we don't recommend you build production apps using it since it isn't fully mature and we haven't prioritized fixing issues in that path, haven't resolved the .NET concerns yet, etc.

So, the UWP story for 3.0 GA would be essentially the same as the story for Preview3 today: it's still not ready for production apps to be built on it.  I hope that clarifies.  No doubt this will be a disappointment to those who want to use WinUI in UWP apps, and for those people I'll state that it's still our intention to open up the UWP pathway as well, but Win32 will be ready first and we don't want to hold back a GA for those customers.

**Comment by mrlacey** [comment]
@ryandemopoulos thanks for confirming

**Comment by mrlacey** [comment]
Does WinUI3 shipping in March 2021 ([source](https://youtu.be/MulUg7iD2-s?t=1687)) affect this proposed timeline?

**Comment by mikebattista** [comment]
See https://github.com/microsoft/TemplateStudio/blob/dev/docs/roadmap.md for our latest roadmap.
