### ISSUE TITLE
Review automated testing

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#4126]
**Is your feature request related to a problem? Please describe.**

Automated testing of the projects generated by templates is slow ([example](https://github.com/microsoft/WindowsTemplateStudio/pull/4077#issuecomment-789834381)) and not 100% reliable. (There are occasional failures and high memory consumption means it's not possible to run all tests from within Visual Studio at the same time.)

In addition to #4045 it will be beneficial review all existing tests (for WPF and UWP generated projects).

As part of the discussions relating to #3753 (MVVM Toolkit replacing MVVMLight & MVVMBasic) there has been mention that after the removal of deprecated frameworks would be a good time to look at making such a change as the removal of support for some frameworks will necessitate a lot of changes in the testing set up anyway.

**Describe the solution you'd like**

Ideally tests will:
- Cover all core/realistic scenarios
- Be as fast as possible (within reason/practicality)
- Simplify the determining of data for running data driven tests (it currently takes several minutes to determine which tests are available.)
- Be able to run on an automated basis
- Be easy to understand, update, and maintain in the future.

**Describe alternatives you've considered**

To not review the current testing set up will mean that tests are infrequently run and so their ability to detect issues quickly will be diminished.
The natural extension of only running tests very infrequently (as seen in many other projects and environments) is to stop running them entirely. This would lead to issues not being detected and a lower quality of product being released.

**Additional context**

This is likely to be a large, complex undertaking that must be carefully organized and structured if other changes are happening to templates at the same time. 

While this work is unlikely to happen in the near-term I have created this to track what is needed and has been discussed elsewhere but wasn't publicly documented.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
|  Yes | Yes | Yes |

**Comment by sibille** [comment]
Thanks for opening this issue and your thoughts on this. 
All automated template tests are run on different build pipelines on a regular basis but I agree that we need to look into the pain points you mention to make local template testing more efficient.

Adding a  few thoughts from our side:

I agree that tests should cover core scenarios, but I can also see value in edge case scenarios as done in OneByOneTests and ProjectValidationTests. Those tests create/build a lot of applications and take very long to execute, but also detect errors from time to time that would be hard to find otherwise.

One thought we had was splitting up tests into different projects or test lists. This would help to make clearer which tests should be executed when and would also improve test detection time.

**Comment by mrlacey** [comment]
We'll need to consider how WinUI3 related tests are added and integrated with existing tests.
Keeping them clearly separate will help with future refactoring.

Oops, looks like I was too late with this suggestion, and the ones that have been added already are closely integrated.

**Comment by mikebattista** [comment]
@mrlacey, with the recent refactoring you did for splitting up the extensions and tests, is there any work remaining here? Or are you happy with the current state of the tests?

**Comment by mrlacey** [comment]
> @mrlacey, with the recent refactoring you did for splitting up the extensions and tests, is there any work remaining here? Or are you happy with the current state of the tests?

Only remaining issue I'm aware of here is fixing the parallelization of the UWP Build tests

**Comment by mikebattista** [comment]
> > @mrlacey, with the recent refactoring you did for splitting up the extensions and tests, is there any work remaining here? Or are you happy with the current state of the tests?
> 
> Only remaining issue I'm aware of here is fixing the parallelization of the UWP Build tests

This is tracked by #4444, so closing this out.
