### ISSUE TITLE
Backbutton disappearing in WinUI 3 Desktop app with NavView and ListDetail Page when resizing the app

### ISSUE THREAD

**Issue by sibille** [microsoft/TemplateStudio#4280]
When you resize an app with a ListDetailView in a WinUI 3 NavigationView the BackButton disappears and re-appears intermittently.

X-Ref: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/4021

**Comment by mikebattista** [comment]
See https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4021#issuecomment-1148928602.

Closing since resolved in Template Studio by changing BackButtonBehavior to Manual in latest released builds.
