### ISSUE TITLE
Should WTS switch to the new style issue templates?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#4317]
The current issue templates for this repo include a single text block with a lot of pre-filled details, headers, and comments. This can be hard to read and fill out as desired. 
An alternative is available and was discussed previously but limited feedback has since been given/discussed.

I have created a separate repo to demonstrate how the new alternative could look: https://github.com/mrlacey/wts-issue-test/issues/new/choose

This will change the way the bug report and feature request forms look. From this:

![image](https://user-images.githubusercontent.com/189547/119808767-5ac6e980-bedc-11eb-8eb7-ea20da5f5bae.png)

to this:

![image](https://user-images.githubusercontent.com/189547/119808682-44b92900-bedc-11eb-881e-cdcd7d91f481.png)

The goal of such a change is to make it easier to create new issues while also ensuring the provision of necessary/required information.

Please feel free to [create new issues in this repo to try out the new experience](https://github.com/mrlacey/wts-issue-test/issues/new/choose).

**Additional context**

_Note that the behavior shown above is in limited, private preview on GitHub but can be used in this repo._

This issue was created to help gain wider feedback. See also https://twitter.com/mrlacey/status/1395661767301373952

**Comment by sibille** [comment]
I like the new issue template, feels much clearer

**Comment by mikebattista** [comment]
Fixed with d547c477a6de19133c248799ea8265a5149c8e8c.
