### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Majorme9821** [microsoft/TemplateStudio#4384]
**Describe the bug**
Every install attempt end with an "Object reference not set to an instance of an object" error
Attempted to install through custom gallery. Both the dev and stable release

**To Reproduce**
Started a new UWP project
Opened extensions manager
In the online tab searched "Windows template"
Downloaded the template
Closed visual studio to install template
VSIX installer window pops up with failed install

**Expected behavior**
The template to be installed

**Screenshots**
**Install Crash Log**
9/18/2021 11:18:43 PM - Microsoft VSIX Installer
9/18/2021 11:18:43 PM - -------------------------------------------
9/18/2021 11:18:43 PM - vsixinstaller.exe version:
9/18/2021 11:18:43 PM - 16.11.12
9/18/2021 11:18:43 PM - -------------------------------------------
9/18/2021 11:18:43 PM - Command line parameters:
9/18/2021 11:18:43 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,J:\Programming\VisualStudio\Microsoft.Templates.vsix
9/18/2021 11:18:43 PM - -------------------------------------------
9/18/2021 11:18:43 PM - Microsoft VSIX Installer
9/18/2021 11:18:43 PM - -------------------------------------------
9/18/2021 11:18:44 PM - System.NullReferenceException: Object reference not set to an instance of an object.
   at VSIXInstaller.SetupExtensions.GetLaunchableInstances(IQuery query)
   at VSIXInstaller.SupportedSKUs.EnumerateIsolatedInstalls(Action`1 callback)
   at VSIXInstaller.SupportedSKUs.AddInstalledLocationBasedSKUs(IntPtr userToken)
   at VSIXInstaller.SupportedSKUs.InitializeSupportedSKUs(IntPtr userToken)
   at VSIXInstaller.ExtensionService.InitializeSupportedSKUs(ICommandLineData cmdLineData, IntPtr duplicatedUserToken)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Additional context**

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :-----Yes------- | :------No----- | :-----No-------|
|  |  | |

**System**

- **VS Version: Community 2019 16.11.3** 
- **WinTS Wizard Version: Unknown** 
- **WinTS Template Version: 4.1.21179.1** 
- **Windows Build: Windows 10 Home v10.0.19043**

**Comment by mrlacey** [comment]
This looks like an error from within the Visual Studio installer.
If you're still having this issue, I recommend [repairing your installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2019) and then reopening this issue if the problem continues.
