### ISSUE TITLE
Review (current) branching strategy

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#4395]
The current branching strategy on the repo relies on the use of 2 main branches.
- **dev** where the latest code is checked in. 
- **release** which has a copy of the latest shipped version of the code.

I think we can do away with the **release** branch when we switch to targeting VS2022.
That is for these reasons:
- There will no longer be a single release as multiple extensions will not always be updated together. This means there is no single "current" release unless all extensions are updated at the same time and there is no need that they always should be.
- Its original purpose was to make it easier to ship minor updates or template updates if needed. We're doing away with template bundling and trying to make the release process faster and easier so the need to do a minor release as a quick fix is far less likely to be needed.
- Releases are all tagged so it should be easy to get the code from a specific release, if needed, without having a separate branch.
- Only having one branch makes branch management really simple and it's always clear where to merge a PR.

In an ideal world, I'd also rename "dev" to "main" but doing this would break all existing docs links and so should be avoided.

There may be reasons to keep the "release" branch that I am not aware of. (Possibly related to the [not publicly documented] release process.)

I'm also keen to hear reasons for other approaches to branching that could be more appropriate.

**Comment by mikebattista** [comment]
I'm open to retiring the release branch. I don't immediately see a reason to keep that given the changes we're making. Let's work out of dev for now and if we hit any issues we can revisit.

**Comment by mikebattista** [comment]
I noticed there are comments in the templates that point to the release branch for doc URIs. We'll need to clean those up if we retire the release branch.

**Comment by mrlacey** [comment]
> I noticed there are comments in the templates that point to the release branch for doc URIs. We'll need to clean those up if we retire the release branch.

It seems a lot more of the links within generated code point to the `release` branch than the `dev` one.
It's probably worth keeping both around to avoid breaking anything.

What about keeping the existing branches (for a to-be-determined period of time) and moving all future work into a new "main" branch?

**Comment by mikebattista** [comment]
> What about keeping the existing branches (for a to-be-determined period of time) and moving all future work into a new "main" branch?

We could create a new "main" branch and keep release and dev around for this year like we're doing with the VS 2019 extension. Then we can consider retiring everything at the beginning of next year. We should update all the VS 2022 templates to point to main before we release the initial version.

**Comment by mrlacey** [comment]
in that there is now a "main" branch that is the default, can this be closed?

**Comment by mikebattista** [comment]
We still need to audit references to the old branches and ensure they are updated to point to main. I've already updated the WinUI and WPF templates in my branches but there are likely other references in UWP templates and elsewhere in the repo.

**Comment by mrlacey** [comment]
For additional background on how I'd like things to work in the future in terms of working with branches. (Based on how we've done things in this repo in the past and with other projects.)

- work should be done in a fork and merged via PR after at least 1 review.
- only in exceptional circumstances should something be merged directly into `main`
- code in `main` should always compile and minimal* tests always pass.
- anything merged that is incomplete (or causes a failing test) should only be merged if a follow-up issue has also been raised.
- Close PRs after merging
