### ISSUE TITLE
Add other Platforms - app models 

### ISSUE THREAD

**Issue by PrestigeDevop** [microsoft/TemplateStudio#4407]
Hi ,  to make rapid app prototyping a little bit easier we would like to see Blazor-MAUI binding as a new platform note by Blazor **app model** I mean Blazor not blazor wasm-server  thing . it would be fall in web category if it's embedded in a traditional  webview  but Blazor has [it's own Controller ](https://visualstudiomagazine.com/articles/2021/04/09/blazorwebview.aspx)  

moreover [blazor maui - binding ](https://docs.microsoft.com/en-us/mobile-blazor-bindings/)with [SHELL](https://github.com/dotnet/maui/issues/4522)

Also another request - if possible - To mod this [Prism Plugin Template  ](https://marketplace.visualstudio.com/items?itemName=BrianLagunas.PrismTemplatePack)for MAUI  

thanks , 

- [ ] .net5 BCL

**Comment by mikebattista** [comment]
There is no Template Studio for MAUI right now, so I'm going to dupe this to https://github.com/microsoft/TemplateStudio/issues/4117 to track it as a feature request for that.
