### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by DeveloperWOW64** [microsoft/TemplateStudio#4409]
### Describe the bug

Perhaps this is because of an issue with the VSIX installer or even VS itself, but I cannot install WTS.

I have had WTS installed on my machine previously; however I reset my PC recently due to problems. I have installed on my clean install MSVS 2022 Community. Upon downloading the VSIX file from the VS marketplace, I run it with the VSIX installer and it fails to install.

### To Reproduce

 1. Download WTS from the VS Marketplace
 2. Open `Microsoft.Templates.vsix`
 3. Wait for it to load 'installing'

### Additional context

![image](https://user-images.githubusercontent.com/71598437/157719811-4c256953-52ab-4e2d-b495-9d70591a48b3.png)

#### Log

`10/03/2022 17:14:10 - Microsoft VSIX Installer
10/03/2022 17:14:10 - -------------------------------------------
10/03/2022 17:14:10 - vsixinstaller.exe version:
10/03/2022 17:14:10 - 17.1.1035-preview2
10/03/2022 17:14:10 - -------------------------------------------
10/03/2022 17:14:10 - Command line parameters:
10/03/2022 17:14:10 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\jfrit\Downloads\Microsoft.Templates.vsix
10/03/2022 17:14:10 - -------------------------------------------
10/03/2022 17:14:10 - Microsoft VSIX Installer
10/03/2022 17:14:10 - -------------------------------------------
10/03/2022 17:14:11 - Initializing Install...
10/03/2022 17:14:11 - Extension Details...
10/03/2022 17:14:11 - 	Identifier         : WindowsTemplateStudio2017.ProRelease.60cee341-5e8e-4db5-a1c4-e3f618500d25
10/03/2022 17:14:11 - 	Name               : Windows Template Studio
10/03/2022 17:14:11 - 	Author             : Microsoft Corporation
10/03/2022 17:14:11 - 	Version            : 4.1.21179.1
10/03/2022 17:14:11 - 	Description        : Windows Template Studio accelerates the creation of new UWP, WPF and WinUI 3 in Desktop apps using a wizard-based UI.
10/03/2022 17:14:11 - 	Locale             : en-US
10/03/2022 17:14:11 - 	MoreInfoURL        : https://github.com/Microsoft/WindowsTemplateStudio/
10/03/2022 17:14:11 - 	InstalledByMSI     : False
10/03/2022 17:14:11 - 	SupportedFrameworkVersionRange : [4.7.2,)
10/03/2022 17:14:11 - 
10/03/2022 17:14:13 - 	SignatureState     : ValidSignature
10/03/2022 17:14:13 - 	SignedBy           : Microsoft Corporation
10/03/2022 17:14:13 - 	Certificate Info   : 
10/03/2022 17:14:13 - 		-------------------------------------------------------
10/03/2022 17:14:13 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
10/03/2022 17:14:13 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
10/03/2022 17:14:13 - 		[Serial Number] : 33000003C93EFB7FE21A3D22B30000000003C9
10/03/2022 17:14:13 - 		[Not Before]    : 15/12/2020 21:24:05
10/03/2022 17:14:13 - 		[Not After]     : 02/12/2021 21:24:05
10/03/2022 17:14:13 - 		[Thumbprint]    : E120FF932F2D4DFB59B1DA16BA7C397119E2DEBF
10/03/2022 17:14:13 - 
10/03/2022 17:14:13 - 	Supported Products : 
10/03/2022 17:14:13 - 		Microsoft.VisualStudio.Community
10/03/2022 17:14:13 - 			Version : [16.2,17.0)
10/03/2022 17:14:13 - 			ProductArchitecture : x86
10/03/2022 17:14:13 - 
10/03/2022 17:14:13 - 	References         : 
10/03/2022 17:14:13 - 		-------------------------------------------------------
10/03/2022 17:14:13 - 		Identifier   : 8EAF6C8E-1283-4EEE-AB6E-F0F087BFCBFD
10/03/2022 17:14:13 - 		Name         : Visual Studio 2019 Update 2 or higher
10/03/2022 17:14:13 - 		Version      : [16.2,17.0)
10/03/2022 17:14:13 - 		MoreInfoURL  : https://www.visualstudio.com/downloads
10/03/2022 17:14:13 - 		Nested       : No
10/03/2022 17:14:13 - 
10/03/2022 17:14:13 - 	Prerequisites      : 
10/03/2022 17:14:13 - 		-------------------------------------------------------
10/03/2022 17:14:13 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
10/03/2022 17:14:13 - 		Name         : Visual Studio core editor
10/03/2022 17:14:13 - 		Version      : [16.0,17.0)
10/03/2022 17:14:13 - 
10/03/2022 17:14:13 - Signature Details...
10/03/2022 17:14:13 - 	Extension is signed with a valid signature.
10/03/2022 17:14:13 - 
10/03/2022 17:14:13 - Searching for applicable products...
10/03/2022 17:14:13 - Found installed product - Global Location
10/03/2022 17:14:13 - Found installed product - Visual Studio Community 2022
10/03/2022 17:14:13 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)`

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 4.1.21179.1
 - Windows Build: 22000.556

**Comment by mikebattista** [comment]
We don't support VS 2022 yet. You should be able to install in VS 2019.

**Comment by mrlacey** [comment]
@DeveloperWOW64 you can track progress to adding support for VS2022 [here](https://github.com/microsoft/TemplateStudio/milestone/33) and at https://github.com/microsoft/TemplateStudio/pull/4408
There are also preview versions of what 2022 support will look like at https://marketplace.visualstudio.com/search?term=%22Template%20Studio%22&target=VS&category=All%20categories&vsVersion=vs2022&sortBy=Relevance
