### ISSUE TITLE
Issues with the WinUICs templates

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#4413]
### Describe the bug

There are issues with the currently defined WinUI (C#) templates:

- Some tests that validate the templates are failing
- The generated code doesn't run and complains about a missing DLL

### To Reproduce

Run test: `TemplateStudioForWinUICs.Tests.TemplateFolderValidationTests.VerifyTemplateFolderContents`

The output highlights that there are files in the templates folder that are not included. They should be part of the generated code or removed.

```ascii
'C:\Users\matt\Documents\GitHub\WindowsTemplateStudio\code\TemplateStudioForWinUICs\Templates\Ft\SettingsStorage\Param_ProjectName\appsettings.json' is not used in the template.
'C:\Users\matt\Documents\GitHub\WindowsTemplateStudio\code\TemplateStudioForWinUICs\Templates\Ft\SettingsStorage\Param_ProjectName\Contracts\Services\ILocalSettingsService.cs' is not used in the template.
'C:\Users\matt\Documents\GitHub\WindowsTemplateStudio\code\TemplateStudioForWinUICs\Templates\Ft\SettingsStorage\Param_ProjectName\Models\LocalSettingsOptions.cs' is not used in the template.
'C:\Users\matt\Documents\GitHub\WindowsTemplateStudio\code\TemplateStudioForWinUICs\Templates\Ft\SettingsStorage\Param_ProjectName\Services\LocalSettingsServicePackaged.cs' is not used in the template.
'C:\Users\matt\Documents\GitHub\WindowsTemplateStudio\code\TemplateStudioForWinUICs\Templates\Ft\SettingsStorage\Param_ProjectName\Services\LocalSettingsServiceUnpackaged.cs' is not used in the template.
```

After shortening all the template paths, I did a quick smoke test to verify everything was still ok.

By creating an app with NavPane and all pages and features, the generated app:
- won't launch the packaged version. 
- will launch the unpackaged version but immediately fails with:

```ascii
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=BlankAdvancedMVVMToolkitAllStyleCop
  StackTrace:
   at BlankAdvancedMVVMToolkitAllStyleCop.Program.XamlCheckProcessRequirements()
   at BlankAdvancedMVVMToolkitAllStyleCop.Program.Main(String[] args) in C:\UIT\MTM\24105055\Proj\BlankAdvancedMVVMToolkitAllStyleCop\BlankAdvancedMVVMToolkitAllStyleCop\obj\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\App.g.i.cs:line 28

```

### Additional context

This is based on https://github.com/microsoft/TemplateStudio/pull/4412 being merged. It's not appropriate to look at that until that is merged.

x-ref #4398 

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.1.2
 - Template Studio Wizard Version: current main path
 - Windows Build: 10 21H1

**Comment by mikebattista** [comment]
The "unused files" are all used. How do the tests define "unused"?

I can run both packaged and unpackaged projects. Have you tried installing VCRedist to see if that fixes your issue? For unpackaged, you need the [WinAppSDK Runtime](https://aka.ms/windowsappsdk/1.0/1.0.1/windowsappruntimeinstall-1.0.1-x64.exe) installed for 1.0.1.

**Comment by mrlacey** [comment]
> The "unused files" are all used. How do the tests define "unused"?

They need to be listed in the template.json file

**Comment by mikebattista** [comment]
As PrimaryOutputs?

**Comment by mrlacey** [comment]
> As PrimaryOutputs?

Yes. 
It may not be the case now, but they used to need to be there to get included in the generated output.
Even if they no longer do, it serves as a useful check to make sure that everything is intentionally included and we don't have any unnecessary files hanging around.

**Comment by mikebattista** [comment]
Fixed with https://github.com/microsoft/TemplateStudio/commit/fe8cddd77946c5f9f997cc713a8e20fa1eb70d61.
