### ISSUE TITLE
Add the Windows App SDK platform to the WinUI extension

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4418]
### Describe the bug

The extension rolls up under Windows while the built-in VS templates roll up under Windows and Windows App SDK. We should match the built-in templates so Template Studio always shows up alongside them regardless of the platform filter.

### To Reproduce

 Create a new project and filter on platform.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mrlacey** [comment]
> The extension rolls up under Windows while the built-in VS templates roll up under Windows and Windows App SDK. We should match the built-in templates so Template Studio always shows up alongside them regardless of the platform filter.

Is this in the new project wizard from VS?

**Comment by mikebattista** [comment]
Yes the filters when you select a project template (so at the Template Studio for WinUI (C#) level).

**Comment by mrlacey** [comment]
Ability to make it do this is incoming: 
![image](https://user-images.githubusercontent.com/189547/160695199-252d074c-a22a-428f-9f8b-bc7ab4170270.png)
