### ISSUE TITLE
Need an easy way to run "Build" tests as part of the CI  

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#4420]
### Is your feature request related to a problem? Please describe.

We have lots of tests.
It takes a LONG time to run them all. So, we have divided them up.

- "Minimum" tests are run as part of PR checks
- "Release" checks are run prior to a release. (They contain things that can't be run until just before release--such as making sure all the latest links to our docs are up to date.)
- "ManualOnly" tests are run prior to release but need to be done manually. Thye can be very slow to run (e.g. coz they require a .NET Native build and then run lots of slow checks.)
- Everything else should be a "Build" related check. These are a series of checks that involve building apps from the templates. We build apps with everything individually and also by combining the different options available (Each framework, each navigation options, and then ALL the other pages, features, etc.) This is also a very large number of tests and take a long time to run.

We have the Minimum checks run as part of the Pul Request process, but we'd also like to be able to run the "Build" checks overnight (when/if anything related has changed.) 
The current configuration of Traits doesn't make this easy.

### Describe the solution you'd like

I propose making the following changes to the way traits are applied to tests.

- Remove all "Type" traits
- Add specific traits for "Build" related tests

this will mean
- All tests should have one and only one trait applied.

### Additional context

Follow on from https://github.com/microsoft/TemplateStudio/pull/4415#issuecomment-1079518834

### Applies to the following platforms:

- [X] WinUI
- [X] WPF
- [X] UWP

**Comment by mrlacey** [comment]
X-Ref #4403

**Comment by mikebattista** [comment]
Is this something you're working on? Outside of finishing the rebranding that I'm working on, I think getting the full suite of tests running, not just Minimum, is the last piece for being ready to ship.

**Comment by mrlacey** [comment]
> Is this something you're working on? Outside of finishing the rebranding that I'm working on, I think getting the full suite of tests running, not just Minimum, is the last piece for being ready to ship.

in progress as we speak

**Comment by mrlacey** [comment]
Here are the changes I'm making:

Every test must have a `Group` "Trait" applied. 

There are 4 basic groups:
- "Minimum"
- "Build"
- "ManualOnly"
- "Release"

A basic group can be applied to a test if it is not specific to an individual extension. 
Most of the tests that meet this requirement are in the "Minimum" group and they relate to logic in the core code, or in the logic shared in the wizard's UI.

In addition to basic groups, there are also platform-specific groups. These groups start with the basic name and then have the platform name as a suffix.

The platform-specific groups are:
- MinimumUWP
- MinimumWinUICpp
- MinimumWinUICs
- MinimumWPF
- BuildUWP
- BuildWinUICpp
- BuildWinUICs
- BuildWPF
- ManualOnlyUWP
- ManualOnlyWinUICpp
- ManualOnlyWinUICs
- ManualOnlyWPF
- ReleaseUWP
- ReleaseWinUICpp
- ReleaseWinUICs
- ReleaseWPF

This allows for 20 possible Group traits.

## Minimum*

Tests in the "Minimum*" groups are run as part of PR acceptance.
These are fundamental basic tests. In general, they should be very quick to run.
The exception to the "quick to run" rule is that there are a few tests for each platform that generate apps with all the available options and test that the generation process works, and that basic formatting and layout requirements of the generated code are met.

## Build*

Tests in the "Build*" groups are run as part of a nightly check on the build server.
These tests generate apps based on multiple different combinations of the available options. In addition to confirming that the apps can be successfully generated they also run additional checks on them.
There are a lot of these tests, and they take a long time to run. (That's why they're not run for PRs.)

## ManualOnly*

Tests in the "ManualOnly*" groups require elevated local privileges or involve automation that takes over the machine they are running on. Examples of things tests in this group do include: verifying a generated app can pass store acceptance (WACK) tests; running automated UI tests to verify basic app navigation; and checking for accessibility issues in the generated app.
Many of these tests take a long time to run and require a machine that isn't used for anything else at the time. (If a test is trying to click on something in the app but a person is also using the machine for another purpose it can easily lead to tests failing.)

## Release*

Tests in the "Release*" groups are also run manually and are meant as a final check prior to releasing a version of an extension. They are only in this group because they cannot be reliably run earlier. Typically, this is because they contain links to documentation on the repo that might not exist until the original PR is checked in. 
They are also run manually because they are often dependent on network connectivity and so any failure must be manually verified.

Anyone creating or modifying templates is expected to run the appropriate tests for the platform they apply to. DO NOT rely on the CI process to test your work. The CI process is a double check on a separate machine.

Only in very special circumstances should a test have more than one group trait.


_Hopefully a version of the above will also be useful in the developer documentation._

**Comment by mikebattista** [comment]
Looks good.

**Comment by mrlacey** [comment]
It should be the case that the new CI process can run all the "Build*" tests in the same way that the PR process runs the "Minimum*" ones.

**Comment by mrlacey** [comment]
@mikebattista the changes I've done in #4434 make it possible to know which tests to run. I'm assuming that you will write and set up the script that runs them.

**Comment by mikebattista** [comment]
Yes I'll update the pipelines.

So by "new CI process" you mean the nightly scheduled pipeline? Not anything tied to a particular CI/commit?

**Comment by mrlacey** [comment]
> So by "new CI process" you mean the nightly scheduled pipeline? Not anything tied to a particular CI/commit?

Yes. 😄

**Comment by mikebattista** [comment]
Nightly pipeline merged with #4435.
