### ISSUE TITLE
Update /_utils/Set-All-Text-File-Template-Encodings.ps1 to support PowerShell Core

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4423]
### Describe the bug

When run in PowerShell Core, it throws errors about unsupported parameters but changes many json, md, and XAML files incorrectly. See https://github.com/microsoft/TemplateStudio/pull/4417#discussion_r837663751 and https://github.com/microsoft/TemplateStudio/pull/4417#issuecomment-1083593722.

```powershell
Changing encoding of C:\TemplateStudio\code\TemplateStudioForUWP\Templates\_comp\_shr\Page.AddTitle.DataGrid\.template.config\template.json
Get-Content: C:\TemplateStudio\_utils\Set-All-Text-File-Template-Encodings.ps1:20
Line |
  20 |     [byte[]]$byte = get-content -Encoding byte -ReadCount 3 -TotalCoun …
     |                                           ~~~~
     | Cannot process argument transformation on parameter 'Encoding'. 'byte' is not a supported encoding
     | name. For information on defining a custom encoding, see the documentation for the
     | Encoding.RegisterProvider method. (Parameter 'name')

InvalidOperation: C:\TemplateStudio\_utils\Set-All-Text-File-Template-Encodings.ps1:23
Line |
  23 |     if ( $byte[0] -eq 0xef -and $byte[1] -eq 0xbb -and $byte[2] -eq 0x …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
```

I believe the below change would migrate the script from Windows PowerShell to PowerShell Core from some cursory testing.

```diff
-   [byte[]]$byte = Get-Content -Encoding byte -ReadCount 3 -TotalCount 3 -Path $Path
+   [byte[]]$byte = Get-Content -AsByteStream -Raw -Path $Path
```

### To Reproduce

Run the script in Windows PowerShell, then run it in PowerShell Core and observe the console output and git diff.

### Applies to the following platforms:

- [X] WinUI
- [X] WPF
- [X] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mrlacey** [comment]
How do I run something in PowerShell Core?
Can we detect this when running? So that if someone tries to run it in a different/unsupported version they can have a suitable warning and now unknowingly break something.

**Comment by mikebattista** [comment]
Just install it https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2.

Yes we can detect the PS Version via $PSVersionTable and fail if the wrong one is used. I'd prefer we migrate things to the latest PowerShell where we can rather than Windows PowerShell.

If you're ok with that for this, I can do that and fail if Windows PowerShell is used.

**Comment by mrlacey** [comment]
I hadn't realized that the version of PowerShell I was using was "Windows PowerShell"

**Comment by mikebattista** [comment]
[#Requires](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7.2) is PowerShell's built-in way to require a specific edition of PowerShell, so replaced explicitly checking `$PSVersionTable` with `#Requires -PSEdition Core`.
