### ISSUE TITLE
Release builds of extensions still show as (Preview)

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4427]
### Describe the bug

The extension still has the `<Preview>true</Preview>` property set in the manifest. Shouldn't that be false for Release builds? Is this flag something we can/should change based on the build configuration?

### To Reproduce

Install a VSIX built with the Release configuration. Observe the name of the extension in Extension Manager as well as the extension.vsixmanifest.

### Applies to the following platforms:

- [X] WinUI
- [X] WPF
- [X] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mrlacey** [comment]
> The extension still has the <Preview>true</Preview> property set in the manifest. Shouldn't that be false for Release builds? Is this flag something we can/should change based on the build configuration?

All this does is set a flag in the marketplace listing.
There is no reason to keep it set once we have an official release.

Having the ability to set the flag to true for Debug builds and false for Release builds will require a custom script. Do we really need one?

**Comment by mikebattista** [comment]
So we can set it to False forever now? I'm fine with that.

**Comment by mikebattista** [comment]
Merged with #4433.
