### ISSUE TITLE
New VS Marketplace publisher ID

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4436]
The existing Windows Template Studio extension is published under WASTeamAccount. You can see this in the URL https://marketplace.visualstudio.com/items?itemName=WASTeamAccount.WindowsTemplateStudio.

I'd like to change this since that's pretty stale and ugly. How about just TemplateStudio? So TemplateStudio.TemplateStudioForWinUICs, TemplateStudio.TemplateStudioForWPF, etc. We can't change it once we ship the new VS 2022 extensions so need to close on a new ID now.

@mrlacey?

**Comment by mrlacey** [comment]
> How about just TemplateStudio?

That works for me

**Comment by mikebattista** [comment]
This is done.
