### ISSUE TITLE
QuickWin: improve PR build times

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#4438]
### Is your feature request related to a problem? Please describe.

The build and test processes we run for each PR take a long time.
Ideally, these should be as quick as possible.

There are (at least) four things we could do to improve these:
- run fewer checks [not desirable]
- rewrite the tests (the biggest contributor to the overall time taken) to run faster [Not a quick fix] 
- Only run tests on the parts of the code that have changed [eventually we'll get to this, but it's a lower priority]
- look for quick fixes to what we currently have [this! do this now!]

### Describe the solution you'd like

I think I can make the `Test Shared Core` and `Test Shared UI` actions faster by adding a new Solution Filter just for them so that the task doesn't need to build things that won't be tested.

Arguably I could add two new solution filters (one for each) but I'd like to keep the number we have small and hopefully manageable. (This can be reviewed at a later date if needed.)

### Describe alternatives you've considered

see above

### Additional context

I think this can save 5-10 minutes and so is definitely worth trying.

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [ ] UWP

**Comment by mrlacey** [comment]
I expect I'll be motivated to look at the conditional execution of individual jobs next time I'm anxiously waiting for a set of PR checks to run 😉

**Comment by mikebattista** [comment]
Merged with #4439.
