### ISSUE TITLE
Pacakage.Appinstaller is included in the unpackaged project templates

### ISSUE THREAD

**Issue by cwruss** [microsoft/TemplateStudio#4440]
### Describe the bug

This is a minor issue that the code/TemplateStudioForWinUICs/Templates/Proj/Default.Blank/wts.ProjectName/Package.appinstaller is being included in projects that will not use this file.

### To Reproduce

 1. Create an unpackaged project template
 2. View solution and see package.appinstaller file
 

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mikebattista** [comment]
This is by design currently though happy to hear thoughts.

Single-project packaging makes it easy to switch between packaged and unpackaged, so while the unpackaged template produces an unpackaged project by default, it's easier to switch to packaged if the files you need for packaging are already in the solution.

**Comment by mikebattista** [comment]
Template Studio is built on top of the underlying platform, and single-project packaging is set up this way.

That said, I'm fine removing these files, but Right-Click -> Add Packaging is not a priority for the upcoming initial release.

**Comment by mrlacey** [comment]
> Template Studio is built on top of the underlying platform, and single-project packaging is set up this way.

This sounds like you're saying that single-project packaging is set up to include a file that isn't needed.

**Comment by mikebattista** [comment]
It allows you to switch between both and doesn't remove package-related files when you switch to the unpackaged configuration.
