### ISSUE TITLE
Deploy is unchecked in the build configurations for packaged projects

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4442]
### Describe the bug

This requires the developer to manually check Deploy in the build configuration or experience a failure the first time they try to F5.

This issue was fixed with the inbox Windows App SDK templates, but after some testing, Template Studio may not be benefitting from the fixes that were made for that, possibly related to its use of the .NET templating engine and how it composes templates together.

### To Reproduce

 1. Create a project with MSIX
 2. F5
 3. Observe the error

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mikebattista** [comment]
From within VS.

**Comment by mikebattista** [comment]
MAUI fixed this in their project system last year via https://github.com/dotnet/maui/issues/2746.

Some other internal guidance on the fix, but this is based on the VS project system.

> Currently for both “Create New Project” and “Add New Project”,  the default state of “Deploy” flag for the new project is “calculated” by this logic:
>     If `<project DOES not support Deploying>`  then  it is set to FALSE.
>     Else if `<project DOES not implement hierarchy property “VSHPROPID_DefaultEnableDeployProjectCfg”>` then it is set to TRUE.
>   Else it is set to the value of “VSHPROPID_DefaultEnableDeployProjectCfg” property.
> 
> So, if you want the [new] project to end-up with “Deploy” checked, make sure that: 
> 1)	Either do not implement VSHPROPID_DefaultEnableDeployProjectCfg (aka return E_NOTIMPL) or if implemented, it returns “VARIANT_TRUE”. 
> 2)	Ensure that project “supports” deployment which means:
> a)	Project does implement IVsDeployableProjectCfg.
> b)	And IVsDeployableProjectCfg->QueryStartDeploy(0, &fSupported, &fReady); succeeds and sets fSupported to true.
>

**Comment by mikebattista** [comment]
@mrlacey do you know how the above guidance might apply here?

**Comment by mrlacey** [comment]
> @mrlacey do you know how the above guidance might apply here?

I'll dig deeper later, but it looks like the MAUI notes on the fix don't apply as they're for the project system. I'll start by looking at what changed in the "official" templates:
https://github.com/microsoft/WindowsAppSDK/commit/b419d6d9d551f8e083f97f647f0e51f654a319a3
https://github.com/microsoft/WindowsAppSDK/commit/085aac80895399f9c73e2a317084a78c02655cff

**Comment by mikebattista** [comment]
Not a ship blocker for initial VS 2022 version. Let's relnote that you need to check the Deploy option in the Build Configuration for packaged apps.

**Comment by mrlacey** [comment]
Initial investigation shows a possible timing issue within VS itself. By slowly stepping through the code in `VSGenShellSolution` the output is as expected. 
If I let it run without any breakpoints then the "deploy" flag isn't set for the default project.

Further investigation is required.
Creating an isolated repro for the issue is likely to be difficult.

**Comment by mrlacey** [comment]
> Not a ship blocker for initial VS 2022 version. Let's relnote that you need to check the Deploy option in the Build Configuration for packaged apps.

@mikebattista was this documented in release notes or known issues? I can't find it mentioned anywhere.

**Comment by mikebattista** [comment]
I added it to the 5.0 release notes.

**Comment by mrlacey** [comment]
> I added it to the 5.0 release notes.

Aah, yes, it is in the [release notes on GitHub](https://github.com/microsoft/TemplateStudio/releases/tag/v5.0) but it would also be useful to link to this from within the extension manifest so that it's easier for people using the extension to find and see this.

**Comment by mrlacey** [comment]
#4562 is a temporary workaround for this problem.
I haven't yet been able to fully isolate the exact cause of the issue. I'm hoping that adding a workaround will avoid people from encountering the issue and that this workaround can be included in the next release. (5.2?)

The actual cause of the issue is either in the WinUI3 project system code that integrates with Visual Studio for the creation of a project. Or, it's a bug directly within Visual Studio.
Determining exactly which it is and being able to create a simple minimal reproduction of the issue will not be a simple task. However, such a task is necessary to escalate to the appropriate team. (And prove it's not an issue with the Template Studio code-base. It could be the case that the underlying issue is in this codebase but having looked through the related parts of the code a lot, I can't see anything. A simple repro would verify this for sure though.)

**Comment by mrlacey** [comment]
> Thanks Matt. This is definitely an annoying bug that degrades the out-of-box experience. Would it be easy to only apply the delay if the project contains the MSIX feature at creation time?

It would require some messy rearchitecting as the relevant bit of code only knows the path to the project file and would need to potentially know about everything selected by the user. For a (hopefully) temporary workaround until there's an external fix, I'd prefer not to change any more code than absolutely necessary.

**Comment by mikebattista** [comment]
Ok. I was hoping that context was available at this point in the code. Agreed we shouldn't go overboard here for a temporary workaround.

**Comment by mikebattista** [comment]
A few clues that may help:

* The `ShouldDeploy` property documented at https://docs.microsoft.com/en-us/dotnet/api/envdte.solutioncontext?view=visualstudiosdk-2022#properties
* `ShouldDeploy` being called already at https://github.com/microsoft/TemplateStudio/blob/80e811bc3edad3e6e3d6bb78b05562e41ce967e8/code/SharedFunctionality.UI/VisualStudio/GenShell/VsGenShellSolution.cs#L153
* A custom post action that can set `ShouldDeploy` to true or false for a given project at https://github.com/microsoft/TemplateStudio/blob/main/code/SharedFunctionality.Core/PostActions/Catalog/AddProjectConfigurationToContextPostaction.cs

My theory is if we add a postaction to the main project template (or the MSIX template) with `deploy` set to `true`, then that will enable Deploy in the Configuration Manager for the project.

Need to consider new project scenarios as well as scenarios where MSIX is added to the project after initial creation.

**Comment by mikebattista** [comment]
Setting the post action appears to fix the issue. Closing out and including in a 5.2.1 servicing update.
