### ISSUE TITLE
Refactor and reenable UWP tests for the nightly build pipeline

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4444]
### Describe the bug

See https://github.com/microsoft/TemplateStudio/pull/4435#issuecomment-1090817372.

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [X] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mrlacey** [comment]
It currently takes >11 hours to run everything!!!!!!

I'll review:
- what can be removed (if anything)
- what can be made to run in parallel

**Comment by mikebattista** [comment]
Refactoring tests not required for VS 2022 initial releases. We will manually run the tests to sign off on the release and keep them disabled in the pipelines.

**Comment by mrlacey** [comment]
Abandoning in view of #4539
