### ISSUE TITLE
WACK tests for WinUI projects are broken

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#4451]
### Describe the bug

The WinUI (C# & c++) WACK tests are currently broken as they still expect a separate packaging project.

I assume this is a side effect of #4398 & #4399

### To Reproduce

 1. Run the WinUICs or WinUICpp WACK tests
 2. See error

### Additional context

I've looked at this for a couple of hours and it's not a quick fix. (Partly because it's slow to run the tests.)

Also, need to update the internal code step that explicitly talks about a packaging project.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mrlacey** [comment]
I'll continue to investigate this but have created this to log the change and to unblock #4449

**Comment by mikebattista** [comment]
Not required for initial 2022 versions.

**Comment by mrlacey** [comment]
Closed by #4530
