### ISSUE TITLE
WinUI: Unhandled exception at 0x76D62991 (combase.dll) when app starts

### ISSUE THREAD

**Issue by mcNets** [microsoft/TemplateStudio#4454]
### Describe the bug

After generating a new project with at least a Navigation pane I receive this exception at the starting point:

```
static void Main(string[] args)
{
    global::WinRT.ComWrappersSupport.InitializeComWrappers();
    global::Microsoft.UI.Xaml.Application.Start((p) => {
        var context = new global::Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(global::Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread());
        global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
        new App();
    });
}
```

I can generate, build and execute a Blank application but if I select a Navigation Pane project, it fails.

That's what I got in the output window:

```
'App2.exe' (CoreCLR: clrhost): Loaded 'Snippets'. 
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown at 0x7534ECB2 (KernelBase.dll) in App2.exe: WinRT originate error - 0x80004002 : 'Unable to cast object of type 'WinRT.ObjectReferenceValue' to type 'WinRT.IObjectReference'.'.
Unhandled exception at 0x76D62991 (combase.dll) in App2.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x12BE5648, 0x00000001).
```

### To Reproduce

 1. Go to Create New Project
 2. Select Template studio for WinIU (C#)
 3. Select Project type: Navigation Pane and click Create
 4. Press F5 
 5. See error

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

Visual Studio: Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.1.4

.NET SDKs installed:
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.104 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64

 - Template Studio Wizard Version:  0.5.3.0

**Comment by mikebattista** [comment]
I'm not able to repro but looks like https://github.com/microsoft/CsWinRT/issues/1162. Can you see if the workarounds listed there help? If not, we should continue the discussion on that issue with the C#/WinRT team.

**Comment by mcNets** [comment]
Adding `<WindowsSdkPackageVersion>10.0.19041.25</WindowsSdkPackageVersion>` and restoring the project solve the issue.

**Comment by mrlacey** [comment]
v0.5.3 is my preview.
The official release (coming soon--I promise) will have all updated references and so should address this.

**Comment by mikebattista** [comment]
Haven't seen this issue reported since the official release has been out, and haven't run into it while testing the upcoming release. Closing out.
