### ISSUE TITLE
Update UX to match WinUI design guidelines

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4463]
### Is your feature request related to a problem? Please describe.

Need to update UX for latest WinUI design guidelines (margins, layouts, styles, etc.).

* [x] Add unique icons per page template in NavigationView (#4488)
  * [x] Page for Blank
  * [x] Globe for WebView
  * [x] List for ListView
  * [x] GridView for ContentGrid
  * [x] PageMarginLandscapeWide for DataGrid
* [x] Remove unnecessary Page, Frame, and Grid Styles and BackgroundColors
* [x] Add custom titlebar required for dark theme and Mica support
* [ ] Add Mica support (moved out to 5.2)
* [x] MenuBar Settings page should follow Notepad's Settings page instead of a flyout

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

**Comment by mrlacey** [comment]
At the very least, this issue needs a link to the guidelines. 
A breakdown of what needs changing is also required so that progress can be monitored and it's possible to evaluate when it's done and that the changes made match what is required.

**Comment by mikebattista** [comment]
There's an internal design review in progress and will list the action items here once that is resolved.

**Comment by mrlacey** [comment]
For additional background information. The NavView icons were previously, deliberately, all the same, to highlight that they should be changed.
Was any consideration given to the possibility of this now being seen as advice or a recommendation that these pages _should_ use these specific icons?

**Comment by mikebattista** [comment]
The TODO comments are still there and have been updated to guide the developer towards how to use the latest Fluent icons, but the out-of-box experience has always looked a bit broken to me, and the designers agreed. Differentiating the icons looks a lot more polished.

**Comment by mikebattista** [comment]
All changes have been merged.
