### ISSUE TITLE
enable SourceGenerators

### ISSUE THREAD

**Issue by Varorbc** [microsoft/TemplateStudio#4474]
### Is your feature request related to a problem? Please describe.

https://github.com/CommunityToolkit/dotnet/tree/main/CommunityToolkit.Mvvm.SourceGenerators

### Applies to the following platforms:

- [X] WinUI
- [X] WPF
- [ ] UWP

**Comment by mrlacey** [comment]
Definitely for WPF & WinUI. 
Possibly for UWP

**Comment by michael-hawker** [comment]
I'd suggest waiting for 8.0 release of the MVVM Toolkit when the incremental source generators are released (there's also new features there and property name changes).

But it should work fine across WPF, UWP, and WinUI 3. In fact, you can create the ViewModels/Models in a .NET Standard library and have everything isolated from the UX layer.

**Comment by mikebattista** [comment]
Thanks. I'll move this to the 5.3 release for tracking.
