### ISSUE TITLE
Update WinUI templates to WinAppSDK 1.1

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4480]
### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

**Comment by mrlacey** [comment]
WinAppSDK 1.1 is currently only in [preview](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#version-11-preview-3-110-preview3). 
Is the intention of this issue to add support while still in preview or is this tied to the official release of WinAppSDK 1.1?

Historically, Template Studio has not included previews in released versions. 


If TS5.1 will include support for WAS1.1 does this mean both will be linked to the same approximate time frame of ["first half of 2022"](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/roadmap.md#upcoming-features--releases) and, therefore, presumably some time in (late) June?

**Comment by mikebattista** [comment]
The next release will align with 1.1 stable.
