### ISSUE TITLE
Cannot view local variables after creating a new WinUI 3 project using "Template Studio for WinUI (C#)"

### ISSUE THREAD

**Issue by bennybroseph** [microsoft/TemplateStudio#4485]
### Describe the bug

I’m unable to view local variables after creating a new WinUI 3 project using “Template Studio for WinUI (C#)”. When stepping through methods I instead get the following error:

> Cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away.

I have verified that I am not in release mode. I have verified that nothing is listed as “Optimized” in the “Modules” debugging window. This issue does not occur when debugging a UWP application created the same way. I have tried this on two different computers and get the same result.

### To Reproduce

 1. Create a new WinUI 3 C# project using "Template Studio for WinUI (C#)"
 2. Selection of template options does not seem to make a difference, so select any.
 3. Set a breakpoint in a method which contains local variables.
 4. Observe that variables are claimed to be optimized away and their values are not displayed.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.1.6
 - Template Studio Wizard Version: 5.0
 - Windows Build: 22000.652 (Occurred on Win10 machine as well)

**Comment by mikebattista** [comment]
I'm not able to repro this. Is there something missing from your repro?

**Comment by bennybroseph** [comment]
The above works for me, but I'll be more specific in case it is not a 100% repro. Keep in mind that I'm working on a project which has a lot more code than just the template and I cannot view the value of any local variables in methods even on lines where their values are being evaluated in expressions.

1. Create a new WinUI 3 C# project using "Template Studio for WinUI (C#)"
2. Select Navigation Pane > MVVM Toolkit.
3. Ensure at least one Blank, Settings, and ListDetails page is added.
4. Finish creating the project using the template.
5. Set at the end scope of "AllOrder" on line 31 of "SampleDataService.cs".
6. Observe that the value of "companies" cannot be viewed within the "local" tab nor by hovering over the variable.

![image](https://user-images.githubusercontent.com/13838608/167981494-6540e70d-7470-41ed-a9b5-c6c23158ec69.png)

**Comment by mikebattista** [comment]
Thanks. If I follow your new steps exactly, I can repro. I think this may be related to MSIX packaging. I was not able to repro with an unpackaged project, which is what I was trying earlier.

Could you try switching your project to unpackaged and see if that helps?

* Change the debug/launch configuration to the `(Unpackaged)` option
* Add `<WindowsPackageType>None</WindowsPackageType>` to the app .csproj
* Replace `LocalSettingsServicePackaged` with `LocalSettingsServiceUnpackaged` in App.xaml.cs
* Install the WinAppSDK Runtime from https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-10
* F5

**Comment by bennybroseph** [comment]
Thank god, this has been plaguing me for over a week. Thank you so much for this workaround!

Is this still a bug or is this just the expected behavior of an MSIX packaged build?

**Comment by mikebattista** [comment]
Awesome. I'll check with the MSIX team as there may be an issue there, but I don't think this is anything Template Studio specific.

**Comment by mikebattista** [comment]
@dianmsft any known issues here with MSIX?

**Comment by mikebattista** [comment]
The issue here was that `PublishReadyToRun` was always enabled even for Debug builds which was optimizing away the local variables. I updated the pubxml files to conditionally set `PublishReadyToRun` based on the build configuration to fix this issue and align with the latest WinAppSDK templates.

If you want to go back to packaged, you can update the `PublishReadyToRun` properties in all the `Properties/PublishProfiles` files to the below. That should enable you to view local variables again when debugging apps with MSIX.

```
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
```
