### ISSUE TITLE
Not running with CommunityToolkit.Mvvm 7.1.2 update

### ISSUE THREAD

**Issue by jader1313** [microsoft/TemplateStudio#4495]
### Describe the bug

After creating a new WuUi 3 project using “Model Studio for Winsui (C#)” and updating Nuget Package CommunityToolkit.mvvm to version 7.1.2, it no longer runs.

### To Reproduce

Create a new WinUI 3 C# project using "Template Studio for WinUI (C#)"
Run project: Ok
Update nuget package CommunityToolkit.Mvvm to 7.1.2
Run project: does not run.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.2
 - Template Studio Wizard Version: 5.0
 - Windows Build: 21H1

**Comment by jader1313** [comment]
Navigation Pane > MVVM Toolkit.
Blank

**Comment by mikebattista** [comment]
If you remove MSIX when you create the project, does it still repro?
