### ISSUE TITLE
Remove self-contained workaround once the platform bug is fixed

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4503]
### Describe the bug

See #4501.

### Applies to the following platforms:

- [x] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by tsvietOK** [comment]
@mikebattista Hey, looks like you deleted project node in commit https://github.com/microsoft/TemplateStudio/commit/e5a771da5728167738047da6b267d25796ea7383
