### ISSUE TITLE
Fix theming issues from removing custom styles

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4510]
### Describe the bug

All project types need to be tested in light and dark theme to make sure they render as expected. Removing custom styles exposed deficiencies in default control behavior.

Pending feedback from WinUI team on the right recommendations.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mrlacey** [comment]
As this is the result of another change, what could be done to prevent similar future changes from causing something else to break?

**Comment by mikebattista** [comment]
These breaks were deliberate. Removing custom styles to expose issues with default behavior was the plan with these changes. Now we're just waiting on feedback from WinUI on the proper changes to make to get the templates looking the way they want.

**Comment by mikebattista** [comment]
Fixed with https://github.com/microsoft/TemplateStudio/pull/4505/commits/93fd1cc617579734751256c4f746fb5e15c0c23c as part of #4505.
