### ISSUE TITLE
Cannot create C# UWP project

### ISSUE THREAD

**Issue by ttustonic** [microsoft/TemplateStudio#4511]
### Describe the bug

I have just installed Template studio for UWP, and now I can't create C# project. VS only offers a Visual Basic project.

### To Reproduce

 1. Go to 'File | New project'
 2. Search for 'Template studio for UWP'
 3. Select C# Language
 4. Template studio for UWP is not listed

### Additional context

Template studio with all languages selected
![uwpall](https://user-images.githubusercontent.com/5532089/169626908-9760be6f-33f9-4183-a1d0-24cfc13f69dc.jpg)
No template studio for C#
![uwpcs](https://user-images.githubusercontent.com/5532089/169626916-5250ffa8-fbc6-452a-99dc-425871a9e7a5.jpg)

![tsinstalled](https://user-images.githubusercontent.com/5532089/169627168-519ba6d7-d9fc-4745-bb2c-1dd630a62207.jpg)

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [X] UWP

### About your setup

 - Visual Studio Version:  Community Version 17.2.1
 - Template Studio Wizard Version: 5.0
 - Windows Build: 19044.1706

**Comment by mikebattista** [comment]
I'm not able to repro. I see both templates. Tried with both 17.2.0 and 17.2.1 with an existing install of the extension and a reinstall.

![image](https://user-images.githubusercontent.com/13860912/169663507-c3f2a466-4638-465a-b52c-e09c822b2c60.png)

**Comment by ttustonic** [comment]
Hmm, strange.
It all worked here a few days ago, but it seems that something went wrong with ver. 5. I uninstalled and reinstalled a few times, but it didn't help.

**Comment by mikebattista** [comment]
Version 5 is the only version of the extension we have shipped for VS 2022. There haven't been any updates or anything that would have regressed the behavior. You're saying you had this working in VS 2022 a few days ago, but now it's not working?

**Comment by ttustonic** [comment]
Oh, I assumed it's a new version, since Marketplace says that last commit was very recently. 
Yes, it worked a few days ago, and now it doesn't. 
It might be VS update, but I think it stopped working even before the VS update.
I don't know if there's any connection betweeen this extension and a similar one (Matt's Template studio), which seems to work fine.

**Comment by mikebattista** [comment]
Interesting. It's possible that @mrlacey's extension and the official one are conflicting. Could you remove both and reinstall the UWP extension?

@mrlacey's extension was a temporary solution for VS 2022 until we were able to ship the official versions, so you shouldn't need that extension anymore.

**Comment by ttustonic** [comment]
I did it a few times, but it didn't help.
But, it works now, after I removed Matts extension for WinUI. I didn't event have Matts UWP extension installed when I made these screenshots.
Thanks, Tom

**Comment by mikebattista** [comment]
Awesome. Glad we got it resolved.

@mrlacey, is there anything we can do in your extensions to avoid conflicts like this from impacting others in the future?

**Comment by mrlacey** [comment]
Reopening and assigning to myself to track further investigation.
If two UWP versions installed I'd assume I'd reused a guid somewhere I shouldn't but if it's my winui extension affecting the official UWP one then that's likely to be something that needs greater investigation
