### ISSUE TITLE
WinUI app won't run

### ISSUE THREAD

**Issue by PhilPJL** [microsoft/TemplateStudio#4512]
### Describe the bug

After creating a new app using Template Studio for WinUI it won't run and fails with 
![image](https://user-images.githubusercontent.com/271656/169642401-cf3284e0-731c-4cac-ac8d-0fe0a01361af.png)

Whereas creating a WinUI app using "Blank App, Packaged (WinUI 3 in Desktop)" works fine.

### To Reproduce

Create app using "Template Studio for WinUI (C#)" without selecting any additional options.
Attempt to run as unpackaged - fails.
Attempt to run as packaged (after checking deploy) - fails.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.2.1
 - Template Studio Wizard Version: 5.0
 - Windows Build: 10.0.19044

**Comment by mikebattista** [comment]
How did you attempt to run as unpackaged? What steps did you take? The error you attached looks like what you get when running unpackaged incorrectly or missing the required runtime.

What error did you get running packaged?

**Comment by PhilPJL** [comment]
Ok I didn't have `<WindowsPackageType>None</WindowsPackageType>`
After adding that I can run the app as 'unpackaged' from VS
![image](https://user-images.githubusercontent.com/271656/169665764-e6c96024-4234-4193-b7e4-2649c8e47928.png)

but now I get these apparently benign warnings:
![image](https://user-images.githubusercontent.com/271656/169665785-2bcca426-a283-4bb7-9266-1df18d03288e.png)
which don't have any associated message or tooltip.

The issue with packaged is that I'd updated Nuget package CommunityToolkit.Mvvm to 7.1.2 (silly me).
The app deploys but won't run because of 
![image](https://user-images.githubusercontent.com/271656/169665966-cb72b8db-2c30-4cb1-b777-58587481725d.png)
After reverting to 7.0.3 it does run.

**Comment by mikebattista** [comment]
Great. Glad you got it working.
