### ISSUE TITLE
I need Windows Template Studio 2017.

### ISSUE THREAD

**Issue by TsweleloS** [microsoft/TemplateStudio#4520]
Good day,

May I please get the installation file for Windows Template Studio 2017.
I really hope you can get it for me.

Thank you.
Tswelelo.S

**Comment by mrlacey** [comment]
Version 3.6 was the last version of Windows Template Studio that supported Visual Studio 2017

The release details (with a copy of the installer--`Microsoft.Templates.vsix`) are available at https://github.com/microsoft/TemplateStudio/releases/tag/3.6.20139.01

Please note that VS2017 is no longer supported and we do not have the capability to support such an old version of this extension. Use at your own risk.
