### ISSUE TITLE
BackRequested (BackButton) e n App.xaml.cs in template Wts blank option

### ISSUE THREAD

**Issue by Javier118** [microsoft/TemplateStudio#4521]
### Is your feature request related to a problem? Please describe.

I want to know how I can implement BackRequest (BackButton in the title bar in App.xaml.cs.

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [X] UWP

**Comment by mikebattista** [comment]
For UWP, use https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Core.SystemNavigationManager?view=winrt-22621.

For WinUI, you'd have to implement it like shown in https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/case-study-1#restoring-back-button-functionality. There is no system back button in the title bar in WinUI/WinAppSDK. To show it in the title bar, you'll need to use a custom title bar as well. The NavigationView and MenuBar projects have all the code for that that you can reuse.
