### ISSUE TITLE
Missing context menu for modifying WPF app in Visual Studio 2022

### ISSUE THREAD

**Issue by tommygebhardtGarmin** [microsoft/TemplateStudio#4535]
I know that the readme says that I should be using vs2019, but I want my app to be in .NET 6 and the extension is available to download in vs2022. I am able to create using the wizard, but no context menu appears on the project for modifications. Is there something that I need to enable?

I'm using vs 2022 17.2.3

Edit: Correcting the comment for what the readme is actually saying

**Comment by mikebattista** [comment]
The Edit context menu I believe was disabled during the VS 2022 migration. @smorin4 and @mrlacey are looking into restoring this functionality and bringing it to the WinUI extension as well.

**Comment by tommygebhardtGarmin** [comment]
I would certainly appreciate that. Thanks!

**Comment by mikebattista** [comment]
This is fixed and will be included in the 5.2 release targeted for July/August.

**Comment by mikebattista** [comment]
Version 5.2 just shipped with the edit project menu reenabled.

See https://github.com/microsoft/TemplateStudio/releases/tag/v5.2 for details. Editing a WPF project created with an older version of the extension will require a few changes to the project to avoid failed merges.
