### ISSUE TITLE
Attempting to install a created App Package fails with error code 0x8000FFFF among other issues.

### ISSUE THREAD

**Issue by bennybroseph** [microsoft/TemplateStudio#4536]
### Describe the bug

After creating an App Package, attempting to install it using the created .msix file results in the error code: 0x8000FFFF. Installing the application using "Install.ps1" and enabling developer mode works but is not reasonable for end users. Also, when setting "Create App Bundle" to "Never", an "Index.html" file and subsequent .appinstaller file are never created even though the output window specifies that it has. Furthermore, if automatic updates were selected and "Copy and Close" is selected, the files are never copied even though the output window again specifies that the operation succeeded. 

### To Reproduce

 1. Create a new WinUI 3 C# project using "Template Studio for WinUI (C#)"
 2. Right click on the project and select "Package and Publish" => "Create App Packages..."
 3. Select "Enable Automatic Updates"
 4. Select "Always" under "Generate app bundle:"
 5. Set a local folder on your computer as the "Installer Location:"
 6. Create the app and select "Copy and Close".
 7. Navigate to the location listed.
 8. Observe that there is no "index.html" or .appinstaller file created.
 9. Attempt to install the .msix file.
 10. Observe error 0x8000FFFF.
 11. Navigate to the Installer location.
 12. Observe that the folder is empty.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version: 17.2.3
 - Template Studio Wizard Version: 5.1
 - Windows Build: 19044.1706

**Comment by mikebattista** [comment]
These are MSIX tooling issues not related to Template Studio.

Generating app bundles is not supported in the VS wizard right now. Does it work with bundles disabled? Do you have more context on the error?

**Comment by bennybroseph** [comment]
I get the same installation error either way. I also unchecked "Enable Automatic Updates". I censored some path/app name info:
App installation failed with error message: Deployment Add operation with target volume C: on Package ID_OF_MY_APP_1.0.0.0_x64__wtta9nmxf3nwp from:  (NAME_OF_MY_APP_1.0.0.0_x64.msix)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x8000ffff)

**Comment by mikebattista** [comment]
I would recommend starting a discussion over at https://techcommunity.microsoft.com/t5/msix/bd-p/MSIX-Discussions with the MSIX team on the expected behavior and any troubleshooting.

You can also turn off MSIX when you create the project to avoid these issues in the meantime.

**Comment by bennybroseph** [comment]
Okay, how can I not use MSIX for projects I've already created so that I can distribute them?

**Comment by mikebattista** [comment]
Follow the steps I shared earlier at https://github.com/microsoft/TemplateStudio/issues/4485#issuecomment-1124483858.

**Comment by bennybroseph** [comment]
Gotcha, thanks for your help with all of this Mike
