### ISSUE TITLE
remove support for uwp

### ISSUE THREAD

**Issue by Varorbc** [microsoft/TemplateStudio#4539]
### Is your feature request related to a problem? Please describe.

[Why migrate to the Windows App SDK?](https://docs.microsoft.com/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/overall-migration-strategy#why-migrate-to-the-windows-app-sdk)

WinUI3 is the future of Windows application development. Will you consider removing support for UWP and focus more on WinUI3 and WPF

### Describe the solution you'd like

remove support for uwp

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [X] UWP

**Comment by mikebattista** [comment]
UWP is still a supported platform so we won't retire that extension anytime soon. We've already split up the extensions per platform so the WinUI extension doesn't carry any baggage from the UWP or WPF extensions. Our future investments and priorities are already focused on the WinUI extension as you suggest.
