### ISSUE TITLE
WinUI Desktop debug fails with: The project needs to be deployed before we can debug

### ISSUE THREAD

**Issue by katdti** [microsoft/TemplateStudio#4547]
### Describe the bug

Creating a out-of-the-box WinUI 5.1 project baesd on defaults fails when selecting Debug (Package) project with:
![image](https://user-images.githubusercontent.com/39122119/174748576-19f62dd5-37cf-4ee9-b661-9b9c51b4e7af.png)

The deploy flag is not set when creating the project from the Visual Studio start dialog
![image](https://user-images.githubusercontent.com/39122119/174749079-1ad7092f-17df-4cda-a5d4-5f5fc6273802.png)

### To Reproduce

 1. Install Template Studio WinUI 5.1 in Visual Studio version 17.2.4.
 2. Close all Visual Studio instances.
 3. Start Visual Studio and select Create a new Project on startup dialog:
![image](https://user-images.githubusercontent.com/39122119/174749582-1f98f9ad-d103-4e32-a19d-79080d78680d.png)
 4. Select "Templates Studio WinUI (C#)" and click create to create a default app: 
![image](https://user-images.githubusercontent.com/39122119/174753278-a91652f9-8dc4-47c2-a1de-9ba1e253ad0c.png)
 5. Click debug project: 
 ![image](https://user-images.githubusercontent.com/39122119/174753492-0cf80529-f6e1-4239-b7ba-cf54fa979dcc.png)
 6. Result:
 ![image](https://user-images.githubusercontent.com/39122119/174748576-19f62dd5-37cf-4ee9-b661-9b9c51b4e7af.png)

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.2.4
 - Template Studio Wizard Version: 5.1
 - Windows Build: 19044

**Comment by mikebattista** [comment]
That's a known issue caused by some timing issue with VS.

https://github.com/microsoft/TemplateStudio/issues/4442
