### ISSUE TITLE
WinUI debug project (unpackaged) fails with: Unable to load DLL 'microsoft.ui.xaml.dll' or one of its dependencies

### ISSUE THREAD

**Issue by katdti** [microsoft/TemplateStudio#4548]
### Describe the bug

Debugging an out-of-the-box C# WinUI project (unpackaged) fails with dialog:
![image](https://user-images.githubusercontent.com/39122119/174756481-b947bb76-339f-4395-82e0-5bb344ef49d9.png)

### To Reproduce

 1. Create new project: 
![image](https://user-images.githubusercontent.com/39122119/174756876-add57d88-33fc-4d1f-b5a5-bc57d549bef0.png)
 2. Select 'Template Studio WinUI (C#)' and click create to create a project based on defaults:
![image](https://user-images.githubusercontent.com/39122119/174757119-c4238f74-9ea7-454e-9e85-8a09a8479daa.png)
 3. Select (Unpackaged) in debug menu and click Debug/Run:
![image](https://user-images.githubusercontent.com/39122119/174757322-ee266371-5b3c-4f90-ab7f-0fcf6c43fca5.png)
 4. Result is dialog:
 ![image](https://user-images.githubusercontent.com/39122119/174756481-b947bb76-339f-4395-82e0-5bb344ef49d9.png)

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version: 17.2.4 
 - Template Studio Wizard Version: 5.1
 - Windows Build: 19044

**Comment by katdti** [comment]
Remove the MSIX Packaging feature does not solve the problem.
Adding Self-Contained feature is also needed. 
MSIX Packaging and Self-Contained features does not co-exists. One and only one feature has to be selected.

After only selecting Self-Contained the project can debug out-of-the-box. It continues to give dependency warnings as shown below - but it runs anyway.

![image](https://user-images.githubusercontent.com/39122119/174978872-df19a3ee-dbe4-4dfb-9e66-42398c0385c5.png)

From build log e.g.

>    Searching for SDK "Microsoft.VCLibs, Version=14.0":
>    Found at search location "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\".
>      Reading SDK manifest file "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\SDKManifest.xml".
>      Targeted configuration and architecture "Debug|x86"
>      Could not find "FrameworkIdentity" attribute "FrameworkIdentity-Debug-x86" in the SDK manifest.

**Comment by mikebattista** [comment]
All combinations are supported. Please read https://docs.microsoft.com/windows/apps/package-and-deploy/deploy-overview for an overview.

For framework-dependent unpackaged, you should have been prompted to install the Windows App SDK runtime. If not, you can install it from the links above. Self-contained removes the requirement to install the runtime since it's carried by the app.

MSIX and self-contained is supported as well. What issues did you hit there?

**Comment by katdti** [comment]
I was prompted and Windows App SDK runtime has been installed.
If I create a C# Template Studio project with defaults selected plus Self-Contained both Package and Unpackaged will debug/run.
If I create a C# Template Studio project with defaults plus Settings and Content Grid page plus Self-Contained feature the Package version debugs/runs but the Unpackaged version fails with:
![image](https://user-images.githubusercontent.com/39122119/175008169-5803c962-ca80-4f9f-a85e-c3f384d32d1a.png)

**Comment by katdti** [comment]
Creating a C# Template Studio project width default and removing the MSIX feature causes this error:
![image](https://user-images.githubusercontent.com/39122119/175010384-c2c71f86-9433-4e6c-8543-b63acdcf5f7b.png)

**Comment by mikebattista** [comment]
You need to remove the MSIX feature from the wizard before you create the project. Hover over the feature in the right pane of the wizard and click the X to remove it.

**Comment by katdti** [comment]
Yes- this is also my conclusion. It is not possible to select both MSIX and Self-Contained feature at the same time
