### ISSUE TITLE
Question to Viewmodel

### ISSUE THREAD

**Issue by saigkill** [microsoft/TemplateStudio#4559]
Sorry for posting. This is my first time working with TemplateStudio and also with MVVM.

The main part for storing and saving the settings are the delivered method:
`public class LocalSettingsServicePackaged : ILocalSettingsService
{
    public async Task SaveSettingAsync<T>(string key, T value)
    {
        ApplicationData.Current.LocalSettings.Values[key] = await Json.StringifyAsync(value);
    }
}`

I have extended the Settings Page with some textboxes like:
`<TextBox x:Uid="Settings_Smtp_ServerBox" Text="{x:Bind ViewModel.SmtpServer}" />
`

In the ViewModel i added some properties like:
`public string SmtpServer
	{
		get => _smtp_server;
		set => SetProperty(ref _smtp_server, value);
	}`

But how can i save the properties content with your settings class?

**Comment by mikebattista** [comment]
If you added a Settings page, you should have `Services/ThemeSelectorService.cs` in your project, which shows an example of how to store settings. This class handles storing the theme setting. You just need to get an instance of the `LocalSettingsServicePackaged` class, then call its `Read` and `Save` methods.

You have a few options to get an instance of the class, in order of preference:

1. Use dependency injection as the `ThemeSelectorService` does. As long as you use `App.GetService` to get instances of your type as the codebase does, the `ILocalSettingsService` member will be populated automatically.
2. Call `App.GetService<ILocalSettingsService>()` to get the singleton instance registered in `App.xaml.cs`
3. Create a new instance with `new LocalSettingsServicePackaged()`
