### ISSUE TITLE
App activation handlers

### ISSUE THREAD

**Issue by techyrajeev** [microsoft/TemplateStudio#4567]
### Is your feature request related to a problem? Please describe.

Implementing the custom app activation handlers

### Describe the solution you'd like

   Can we get sample code with activation handlers implemented, as in WPF it is not quite straight forward to implement activation handlers?
// Activation Handlers

   // Core Services

### Applies to the following platforms:

- [ ] WinUI
- [X] WPF
- [ ] UWP

**Comment by mikebattista** [comment]
Toast Notifications implements an activation handler so I would recommend adding that to the project for an example.

There's also some documentation at https://github.com/microsoft/TemplateStudio/blob/main/docs/UWP/activation.md. In short, you'll need to implement a class in the Activation folder that implements IActivationHandler, then you'll need to register that class in ConfigureServices in App.xaml.cs. Follow what Toast Notifications does.

**Comment by techyrajeev** [comment]
"Toast Notifications" - can you please share links for the same, it will be really helpful @mikebattista ?

**Comment by mikebattista** [comment]
It's a feature in the Template Studio wizard you can enable when you create the project.

**Comment by techyrajeev** [comment]
Got it, thanks a lot
