### ISSUE TITLE
WinUI3: Default Core project targets .NET Standard 2.0

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/TemplateStudio#4568]
### Describe the bug

The new project targets .NET Standard 2.0.

### To Reproduce

1- Create a new app selecting NavigationView
2- Go in the property of the project App1.Core.

It targets .NET Standard 2.0. VS does not even allow to change it to .NET 6.0.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.2.5
 - Template Studio Wizard Version: 5.1

**Comment by mikebattista** [comment]
If you set `<TargetFramework>net6.0</TargetFramework>` manually in the project file, does that work?

**Comment by ArchieCoder** [comment]
Yes it does work. I will let you close or not the issue. A new dev not familiar to the platform might be puzzled when adding nugets that targets Core.

**Comment by mikebattista** [comment]
I will update the project in the templates as well. Thanks.

**Comment by mikebattista** [comment]
Version 5.2 just shipped which contains this change.
