### ISSUE TITLE
Metadata error

### ISSUE THREAD

**Issue by DDungDDungTiger** [microsoft/TemplateStudio#4574]
### Describe the bug
AppxManifest.xml

now
Metadata xmlns="http://schemas.microsoft.com/appx/developer/windowsTemplateStudio"

i fixed it
Metadata xmlns="http://schemas.microsoft.com/appx/developer/templatestudio"

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [X] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mikebattista** [comment]
What is your repro?

**Comment by DDungDDungTiger** [comment]
TempletStudio UWP maked this code

AppxManifest.xml

`<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:genTemplate="http://schemas.microsoft.com/appx/developer/templatestudio" IgnorableNamespaces="uap mp genTemplate build" xmlns:build="http://schemas.microsoft.com/developer/appx/2015/build">
  
  <Identity Name="8A5984E2-FF8A-4A8B-AB7C-EFD350C2C49F" Publisher="CN=ATIGER" Version="1.0.0.0" ProcessorArchitecture="x86" />
  <mp:PhoneIdentity PhoneProductId="8A5984E2-FF8A-4A8B-AB7C-EFD350C2C49F" PhonePublisherId="00000000-0000-0000-0000-000000000000" />
  <Properties>
    <DisplayName>XAML_test</DisplayName>
    <PublisherDisplayName>ATIGER</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.18362.0" MaxVersionTested="10.0.19041.0" />
    <PackageDependency Name="Microsoft.NET.CoreRuntime.2.2" MinVersion="2.2.29713.2" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
    <PackageDependency Name="Microsoft.NET.CoreFramework.Debug.2.2" MinVersion="2.2.29301.2" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
  </Dependencies>
  <Resources>
    <Resource Language="EN-US" />
  </Resources>
  <Applications>
    <Application Id="App" Executable="XAML_test.exe" EntryPoint="XAML_test.App">
      <uap:VisualElements DisplayName="ms-resource:AppDisplayName" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo.png" Description="ms-resource:AppDescription" BackgroundColor="transparent">
        <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png" />
        <uap:SplashScreen Image="Assets\SplashScreen.png" />
      </uap:VisualElements>
      <Extensions></Extensions>
    </Application>
  </Applications>
  <Capabilities>
    <Capability Name="internetClient" />
  </Capabilities>
  <genTemplate:Metadata>
    <genTemplate:Item Name="generator" Value="Template Studio" />
    <genTemplate:Item Name="wizardVersion" Version="v5.1" />
    <genTemplate:Item Name="projectType" Value="Blank" />
    <genTemplate:Item Name="framework" Value="Prism" />
    <genTemplate:Item Name="platform" Value="Uwp" />
  </genTemplate:Metadata>
  <Metadata xmlns="http://schemas.microsoft.com/appx/developer/windowsTemplateStudio">
    <Item Name="generator" Value="Template Studio" />
    <Item Name="projectType" Value="Blank" />
    <Item Name="framework" Value="Prism" />
    <Item Name="platform" Value="Uwp" />
  </Metadata>
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>CLRHost.dll</Path>
        <ActivatableClass ActivatableClassId="Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>
  <build:Metadata>
    <build:Item Name="TargetFrameworkMoniker" Value=".NETCore,Version=v5.0" />
    <build:Item Name="VisualStudio" Version="17.0" />
    <build:Item Name="VisualStudioEdition" Value="Microsoft Visual Studio Community 2022" />
    <build:Item Name="OperatingSystem" Version="10.0.19041.1766 (WinBuild.160101.0800)" />
    <build:Item Name="Microsoft.Build.AppxPackage.dll" Version="17.2.32427.441" />
    <build:Item Name="ProjectGUID" Value="{8AE48972-B65D-49E5-86C3-FC7C86C8124E}" />
    <build:Item Name="OptimizingToolset" Value="None" />
    <build:Item Name="TargetRuntime" Value="Managed" />
    <build:Item Name="Microsoft.Windows.UI.Xaml.Build.Tasks.dll" Version="10.0.19041.685" />
    <build:Item Name="MakePri.exe" Version="10.0.19041.685 (WinBuild.160101.0800)" />
  </build:Metadata>
</Package>`

ERROR messege

심각도	코드	설명	프로젝트	파일	줄	비표시 오류(Suppression) 상태
오류		유효성 검사 오류입니다. error C00CE014: App manifest validation error: The app manifest must be valid as per schema: Line 44, Column 4, Note: The schema for MaxVersionTested specified does not recognize XML fields with namespace "http://schemas.microsoft.com/appx/developer/windowsTemplateStudio". Please ensure that you have the correct MaxVersionTested specified. Reason: 부모 요소 '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Package'의 콘텐츠 모델에 따르면 '{http://schemas.microsoft.com/appx/developer/windowsTemplateStudio}Metadata'은(는) 예기치 않은 요소입니다.	XAML_test	C:\Users\ATIGER\source\repos\XAML_test\XAML_test\bin\x86\Debug\AppxManifest.xml		

I fixed 

`<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:genTemplate="http://schemas.microsoft.com/appx/developer/templatestudio" IgnorableNamespaces="uap mp genTemplate build" xmlns:build="http://schemas.microsoft.com/developer/appx/2015/build">
  
  <Identity Name="8A5984E2-FF8A-4A8B-AB7C-EFD350C2C49F" Publisher="CN=ATIGER" Version="1.0.0.0" ProcessorArchitecture="x86" />
  <mp:PhoneIdentity PhoneProductId="8A5984E2-FF8A-4A8B-AB7C-EFD350C2C49F" PhonePublisherId="00000000-0000-0000-0000-000000000000" />
  <Properties>
    <DisplayName>XAML_test</DisplayName>
    <PublisherDisplayName>ATIGER</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.18362.0" MaxVersionTested="10.0.19041.0" />
    <PackageDependency Name="Microsoft.NET.CoreRuntime.2.2" MinVersion="2.2.29713.2" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
    <PackageDependency Name="Microsoft.NET.CoreFramework.Debug.2.2" MinVersion="2.2.29301.2" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
  </Dependencies>
  <Resources>
    <Resource Language="EN-US" />
  </Resources>
  <Applications>
    <Application Id="App" Executable="XAML_test.exe" EntryPoint="XAML_test.App">
      <uap:VisualElements DisplayName="ms-resource:AppDisplayName" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo.png" Description="ms-resource:AppDescription" BackgroundColor="transparent">
        <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png" />
        <uap:SplashScreen Image="Assets\SplashScreen.png" />
      </uap:VisualElements>
      <Extensions></Extensions>
    </Application>
  </Applications>
  <Capabilities>
    <Capability Name="internetClient" />
  </Capabilities>
  <genTemplate:Metadata>
    <genTemplate:Item Name="generator" Value="Template Studio" />
    <genTemplate:Item Name="wizardVersion" Version="v5.1" />
    <genTemplate:Item Name="projectType" Value="Blank" />
    <genTemplate:Item Name="framework" Value="Prism" />
    <genTemplate:Item Name="platform" Value="Uwp" />
  </genTemplate:Metadata>
  <Metadata xmlns="http://schemas.microsoft.com/appx/developer/templatestudio">
    <Item Name="generator" Value="Template Studio" />
    <Item Name="projectType" Value="Blank" />
    <Item Name="framework" Value="Prism" />
    <Item Name="platform" Value="Uwp" />
  </Metadata>
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>CLRHost.dll</Path>
        <ActivatableClass ActivatableClassId="Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>
  <build:Metadata>
    <build:Item Name="TargetFrameworkMoniker" Value=".NETCore,Version=v5.0" />
    <build:Item Name="VisualStudio" Version="17.0" />
    <build:Item Name="VisualStudioEdition" Value="Microsoft Visual Studio Community 2022" />
    <build:Item Name="OperatingSystem" Version="10.0.19041.1766 (WinBuild.160101.0800)" />
    <build:Item Name="Microsoft.Build.AppxPackage.dll" Version="17.2.32427.441" />
    <build:Item Name="ProjectGUID" Value="{8AE48972-B65D-49E5-86C3-FC7C86C8124E}" />
    <build:Item Name="OptimizingToolset" Value="None" />
    <build:Item Name="TargetRuntime" Value="Managed" />
    <build:Item Name="Microsoft.Windows.UI.Xaml.Build.Tasks.dll" Version="10.0.19041.685" />
    <build:Item Name="MakePri.exe" Version="10.0.19041.685 (WinBuild.160101.0800)" />
  </build:Metadata>
</Package>`

44 line fixed
