### ISSUE TITLE
FooterMenuItem header not changing

### ISSUE THREAD

**Issue by Foxlider** [microsoft/TemplateStudio#4578]
### Describe the bug

While using the WinUI Template Studio C#

When navigating to a page contained in the footer of the NavigationView, the header won't rename itself

### To Reproduce

 1. Add multiple pages with the Template Studio
 2. Move one of the mages from the <NavigationView.MenuItems> to the <NavigationView.FooterMenuItems>
 3. Launch and navigate
 4. Header won't change when navigating to the footer page

### Additional context

Console page
![image](https://user-images.githubusercontent.com/19773387/179773293-aa2e35e0-3486-4895-8aae-91141a002490.png)

Navigate to footer "About" page
![image](https://user-images.githubusercontent.com/19773387/179773157-499601e4-65e2-4a71-b51f-82b8c8709e79.png)

Works well when the page is in the MenuItems
![image](https://user-images.githubusercontent.com/19773387/179773901-e1a43a8c-705f-4853-a4cb-a9e8cbfcd979.png)

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.3.0 Preview 3.0
 - Template Studio Wizard Version: 5.1
 - Windows Build: 19044.1766

**Comment by mikebattista** [comment]
Thanks for filing. I found the bug.

In `NavigationViewService.GetSelectedItem`, change the `return` statement to the below to include the FooterItems.

`return GetSelectedItem(_navigationView.MenuItems, pageType) ?? GetSelectedItem(_navigationView.FooterMenuItems, pageType);`
