### ISSUE TITLE
Link to UnhandledExceptionsEventArgs goes to 404

### ISSUE THREAD

**Issue by CesGan** [microsoft/TemplateStudio#4580]
### Describe the bug

This link goes to 404
https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.unhandledexceptioneventargs
```
    private void App_UnhandledException(object sender, UnhandledExceptionEventArgs e)
    {
        // TODO: Log and handle exceptions as appropriate.
        // For more details, see https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.unhandledexceptioneventargs.
    }
```

### To Reproduce

1) Create a template on for WinUI(C#)
2) Go to App.xaml.cs

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mikebattista** [comment]
This will be fixed in the next update. New link is https://docs.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.application.unhandledexception.
