### ISSUE TITLE
Manage user secrets not working

### ISSUE THREAD

**Issue by suchja** [microsoft/TemplateStudio#4586]
### Describe the bug

In a WinUI3 project (without Template Studio) it is possible to let VisualStudio create the required `UserSecretsId` in the csproj and the *secrets.user* file. This is possible by simply using the *"Manage user secrets"* menu entry on the context menu of the application project.

Although the VS UI behavior in a Template Studio WinUI3 project is similar, neither the `UserSecretsId` is generated in the csproj nor the *secrets.user* file.

### To Reproduce

 1. create a new default project with template studio WinUI 
 2. open context menu on application project (not *core* project)
 3. select *Manage user secrets*
 4. choose *yes* in the upcoming dialog
 5. Verify that csproj file is not changed and secrets.user file is not automatically opened in VS 2022

### Additional context

It is easiest to reproduce the error by using git.

I haven't tried to reproduce this issue with WPF or UWP.

Initializing and adding user secrets via the command line (e.g. `dotnet user-secrets init`) works without issues.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.2.6
 - Template Studio Wizard Version: 5.2.1 (WinUI)
 - Windows Build: 22000.832 (Windows 11 21H2)

**Comment by mikebattista** [comment]
If you add an explicit package reference to https://www.nuget.org/packages/Microsoft.Extensions.Configuration.UserSecrets/6.0.1 before selecting Manage User Secrets, does everything work as expected?

**Comment by mikebattista** [comment]
https://developercommunity.visualstudio.com/t/Manage-User-Secrets-context-menu-option/10133874?port=1025&fsid=8514a84c-acc4-4ee2-9148-986d9261d325&entry=problem

**Comment by mikebattista** [comment]
Confirmed the bugs are in VS here. The above Developer Community issue will track the fixes.

A workaround in the meantime is to add an explicit package reference to https://www.nuget.org/packages/Microsoft.Extensions.Configuration.UserSecrets/6.0.1 before selecting Manage User Secrets.

**Comment by suchja** [comment]
Great. Thanks!

**Comment by mikebattista** [comment]
This is fixed in 17.4 Preview 2.
