### ISSUE TITLE
MyService fails to register in WinUI template

### ISSUE THREAD

**Issue by gmgallo** [microsoft/TemplateStudio#4591]
### Describe the bug

I'm trying to add a new service to a WinUI template. Created a simple IMyService.cs, and concrete MyService.cs following the pattern of the framework generated services:

```
/* IMyService.cs file */
public interface IMyService
{
    string Hello
    {
        get;
    }
}

/* MyService.cs file */
public class MyService : IMyService
{
    public string Hello
    {
        get => _hello;
    }
    private string _hello = "Hi there from MyService!";
     
    private readonly ILocalSettingsService _localSettingsService;

    public MyService(ILocalSettingsService localSettingsService)
    {
        _localSettingsService = localSettingsService;
    }
}
```
 Added it to the list of sevice configuration in App.xaml.cs:
```

  Host = Microsoft.Extensions.Hosting.Host.
        CreateDefaultBuilder().
        UseContentRoot(AppContext.BaseDirectory).
        ConfigureServices((context, services) =>
        {
              // Other framework generated services
               services.AddSingleton<IMyService, MyService>();
            
              // Views and ViewModels
               services.AddTransient<DashboardViewModel>();

             // Configuration
              services.Configure<LocalSettingsOptions>(context.Configuration.GetSection(nameof(LocalSettingsOptions)));
        }).Build();

```
Then I try to use this service in one of the pages:
```
public sealed partial class DashboardPage : Page
{
    public DashboardViewModel ViewModel
    {
        get;
    }
    public MyService myService
    {
        get;
    }
   public DashboardPage()
    {
       // View model loads OK
        ViewModel = App.GetService<DashboardViewModel>();

       // **The next line trhows an exception: "MyService needs to be registered in ConfigureServices within App.xaml.cs."**
        myService = App.GetService<MyService>();

        InitializeComponent();
    }
}
```
The application compiles without errors and runs to the point where it tries to request the service from App. 
Both service files have the same locations and namespaces of the other interface and implementation files.
Am I missing a specific requirement for a Service or other step in the registration?

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  2022
 - Template Studio Wizard Version: latest
 - Windows Build:  1942

**Comment by mikebattista** [comment]
You need to request the interface, not the class.

`App.GetService<IMyService>()`

**Comment by gmgallo** [comment]
I'm afraid that this is not the correct answer. 
If I change it to the interface it has to be cast to MyService to sattisfy the syntax or it won't compile:

![image](https://user-images.githubusercontent.com/11802515/186802162-99329eaf-da94-4df9-bb0c-0bfca82a4dcb.png)

That departs from the pattern shown in all template generated pages. Look carefully at all the pages in my project, there are five of them, including the Shell page that understandinbly is different. All other pages request the class, not the interface:

 ```
  // The dashboard page with IMyService added
    public DashboardViewModel ViewModel
    {
        get;
    }
    public MyService myService
    {
        get;
    }
    public DashboardPage()
    {
        ViewModel = App.GetService<DashboardViewModel>();
        myService = (MyService?)App.GetService<IMyService>();
    }
   // The configuration page
    public ConfigurationPage()
    {
        ViewModel = App.GetService<ConfigurationViewModel>();
        InitializeComponent();

        // more initalization code  ...
    }
    // The logs pagge
    public LogsPage()
    {
        ViewModel = App.GetService<LogsViewModel>();
        InitializeComponent();
    }
    // The settings page
    public SettingsPage()
    {
        ViewModel = App.GetService<SettingsViewModel>();
        InitializeComponent();
    }
    // the shell page is different
    public ShellPage(ShellViewModel viewModel)
    {
        ViewModel = viewModel;
        InitializeComponent();
    }
```
MyService is not different than any of the other services, actully is a copy of another service where I removed all non public memebes. why is not working?

**Comment by mikebattista** [comment]
Your types are still not in sync. Use interfaces or use the class. Change the type of the `myService` Property or register the class differently. The generated code shows examples of both.
