### ISSUE TITLE
When Light theme is used, the top bar should also be light

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/TemplateStudio#4593]
### Describe the bug

![image](https://user-images.githubusercontent.com/1608424/186683997-a043e1a1-3065-498e-b5cd-d8e52bea4871.png)

### To Reproduce

1. Create new UWP template studio project with Settings feature.

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [X] UWP

### About your setup

All latest official releases

**Comment by mrlacey** [comment]
I think this is a Windows bug/feature where the Title bar is always colored based on the system theme. 
This is not something Template Studio is adding to the generated code.
WinUI3 works around this by using a completely custom titlebar. I'm not sure a change in Template Studio is warranted, or what it should be if one was.

**Comment by ArchieCoder** [comment]
In my app, my custom title bar uses the light color but it hides the buttons! I will see if I can make the buttons in another color.

![image](https://user-images.githubusercontent.com/1608424/186699290-b889d666-0be3-4601-a27b-43c8793974dd.png)
