### ISSUE TITLE
How to change the Header for all pages reachable over navigation items?

### ISSUE THREAD

**Issue by dreammaster38** [microsoft/TemplateStudio#4603]
I have a problem. I used Template studio to gernerate a project stub. Everything worked great and I could start to change things to my need.

But now I like to change the name of the item in NavigationViewItem and the name shown in the page itself.

but i don't now how...

In the picture below I want to change the text "Main" into something else.

![image](https://user-images.githubusercontent.com/834612/198296229-19c9cccc-9ab0-4594-8fa8-4e158495904e.png)

>Thank you for your feedback.

**Comment by dreammaster38** [comment]
I found the  solution:

`
 TODO: Update item titles by updating <x:Uid>.Content entries in Strings/en-us/Resources.resw.
                https://docs.microsoft.com/windows/uwp/app-resources/localize-strings-ui-manifest#refer-to-a-string-resource-identifier-from-xaml
`

**Comment by mikebattista** [comment]
Yes that is correct. Closing out.
