### ISSUE TITLE
Update to WinAppSDK 1.2 and WinUIEx 2.0

### ISSUE THREAD

**Issue by mikebattista** [microsoft/TemplateStudio#4611]
### Describe the bug

Update to the latest releases.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mikebattista** [comment]
@dotmorten is that true?

**Comment by dotMorten** [comment]
No, see https://github.com/dotMorten/WinUIEx/issues/95#issuecomment-1371022131

**Comment by SoftEntwickler** [comment]
Then the TemplateStudion needs to be updated to use WinUIEx.WindowManager.PersistenceStorage.

**Comment by dotMorten** [comment]
@SoftEntwickler yes. This feature was specifically added last week by request of template studio - give them a chance to catch up.
