### ISSUE TITLE
[Question] How to add a login page?

### ISSUE THREAD

**Issue by gong-chengxiao** [microsoft/TemplateStudio#4612]
I want to add a login page to do some verify work before main pages loaded.

**What I did**

I found in ActivationService.cs:

```C#
public async Task ActivateAsync(object activationArgs)
{
    // Execute tasks before activation.
    await InitializeAsync();

    // Set the MainWindow Content.
    if (App.MainWindow.Content == null)
    {
        _shell = App.GetService<ShellPage>();
        App.MainWindow.Content = _shell ?? new Frame();
    }

    // Handle activation via ActivationHandlers.
    await HandleActivationAsync(activationArgs);

    // Activate the MainWindow.
    App.MainWindow.Activate();

    // Execute tasks after activation.
    await StartupAsync();
}
```

The I replace the shell page to my login page:

```c#
// Set the MainWindow Content.
if (App.MainWindow.Content == null)
{
    _login = App.GetService<LoginPage>();
    App.MainWindow.Content = _login ?? new Frame();
    //_shell = App.GetService<ShellPage>();
    //App.MainWindow.Content = _shell ?? new Frame();
}
```

When login successes, I use the same way to navigate to shell page:

```c#
UIElement shell = App.GetService<ShellPage>();
App.MainWindow.Content = shell ?? new Frame();
```

It works , but there are some problem:

* Theme switching function does not work, only light theme displays properly
* Doesn't automatically navigate to the 'Home' page, but a bald page

So how can I add a login page correctly?

**Comment by mikebattista** [comment]
Can you provide more details on theme switching not working? Is it just the login page that doesn't support theming or the whole app? Screenshots would be helpful.

**Comment by gong-chengxiao** [comment]
The whole app does not work as expected in dark mode. Same as https://github.com/microsoft/microsoft-ui-xaml/issues/7801, the text switches to white, but the backgroud switching meets problem.

![image](https://user-images.githubusercontent.com/76580793/210477812-c80d9e25-7f0c-45d5-9c79-cc350ce9e494.png)

**Comment by mikebattista** [comment]
The UWP and WPF extensions implement Forced Login which is what you're trying to build. You may find some clues in how they implement this or at least a different approach to try that may not have these issues.
