### ISSUE TITLE
Adding a TemplateStudio for WPF project in a solution that already contains a .Core project will mess up its dependencies

### ISSUE THREAD

**Issue by nicop4** [microsoft/TemplateStudio#4617]
### Describe the bug

I developed a CLI app named `MyApp-cli` in a solution containing a `MyApp.Core` class library project for all the core stuff.

When I added a TemplateStudio for WPF project named `MyApp` to the solution it totally messed up the existing `MyApp.Core` project.

* `TargetFramework` was changed from `net6.0` to `netstandard2.0`
* Any nuget package referenced disappeared
* Any referenced local project was removed
* all `using` statements were reordered (nothing removed but confusing when trying to understand what has changed

This is most likely due to the fact that the extension wants to create a `.Core` project, and it conflicts with the existing one.

Not tested with other platforms than WPF.

### To Reproduce

 1. Create a project MyApp with a MyApp.Core class library in it
 2. Add nuget packages
 3. [Create another lib class and add it as a referenced project in MyApp.Core]
 5. Add a TemplateStudio for WPF project with no specific option, just click create
 6. Et voilà

### Additional context

MyApp.Core.csproj file prior adding the TemplateStudio project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>MyApp.Core</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\OtherClassLib.csproj" />
  </ItemGroup>
</Project>
``` 

After adding the TemplateStudio project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>MyApp.Core</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
</Project>
```

Example of changes in the `using` statements in a class as git diff:
```diff
﻿-using MyApp.Core.Application;
-using System.Collections.Generic;
﻿+using System.Collections.Generic;
using System.IO;

+using MyApp.Core.Application;
+
```

### Applies to the following platforms:

- [ ] WinUI
- [X] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  VS2022 17.4.3
 - Template Studio Wizard Version: 5.2
 - Windows Build: 21H2 19044.2364

**Comment by nicop4** [comment]
Another solution that we did is simply to reset changes to our .Core project files to the previous commit.
I suppose we could this easily because we did not use any option from the wizard so no code was actually added to our .Core project. And that we had a git commit to reset to :)

I would suggest to include this warning in the documentation of the project as a Gotcha or something like that. I understand it could be a lot of work to handle this use case.

**Comment by mikebattista** [comment]
I agree with @mrlacey that this is an edge case. The majority use case for Template Studio is to create a new application in a new solution.

Another workaround would be to rename your existing .Core project before adding the Template Studio project to the solution, then merge the two .Core projects together. That would at least allow you to work in the existing solution and avoid creating a separate one.
