### ISSUE TITLE
Support Visual Studio Professional 2022

### ISSUE THREAD

**Issue by Vchintapatla** [microsoft/TemplateStudio#4625]
### Describe the bug

[dd_VSIXInstaller_20230209064606_4288.log](https://github.com/microsoft/TemplateStudio/files/10695494/dd_VSIXInstaller_20230209064606_4288.log)

I am getting error when installing the visx file on my Windows 11 machine having Visual Studio Professional 2022 preview. I have attached the error log for reference.

### To Reproduce

 1. Download the visx file.
 2. Double Click to install
 3. Error displayed 
 4. See log file for more details

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.5 (Profressional)
 - Template Studio Wizard Version: 5.2.1
 - Windows Build: 11

**Comment by mrlacey** [comment]
@Vchintapatla Can i assume you're using a [Windows Developer SDK device](https://www.microsoft.com/en-us/d/windows-dev-kit-2023/94K0P67W7581) or something else that is ARM based?
