### ISSUE TITLE
Program Indent style need to change, very long time there no new release????

### ISSUE THREAD

**Issue by manusoft** [microsoft/TemplateStudio#4626]
### Is your feature request related to a problem? Please describe.

Programming style (indent) look like this using C#11.0

public string Hello
{
    get; set;
}

### Describe the solution you'd like

need one line like below. 
public string Hello { get; set;}

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

**Comment by mikebattista** [comment]
There's a .editorconfig in the root folder of the generated solution that can control code style. Are you able to update this in your project to achieve the desired indent style?

**Comment by manusoft** [comment]
Yes, thanks bro.
