### ISSUE TITLE
The  foreground of App name always white

### ISSUE THREAD

**Issue by XiaoYQ-GitHub** [microsoft/TemplateStudio#4629]
### Describe the bug

The  foreground of App name always white No matter which theme

### Applies to the following platforms:

- [ ] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  
 - Template Studio Wizard Version: 
 - Windows Build:

**Comment by mikebattista** [comment]
Duplicate of #4630
