### ISSUE TITLE
Update Template Studio (WinUI) to use `SystemBackdrop = new MicaBackdrop();`

### ISSUE THREAD

**Issue by myokeeh** [microsoft/TemplateStudio#4641]
https://github.com/microsoft/WindowsAppSDK/issues/3408

Windows App SDK 1.3 Experimental 1: 1.3.230202101-experimental1 introduced `SystemBackdrop = new MicaBackdrop();`
 i. lieu of 

    <windowex:WindowEx.Backdrop>
        <windowex:MicaSystemBackdrop/>
    </windowex:WindowEx.Backdrop>

**Comment by mikebattista** [comment]
We don't take dependencies on experimental builds. When it ships we can consider migrating.

**Comment by Mysterious-Dev** [comment]
@dotMorten, for this, have you any ETA for an update of WinUIEx for Windows App SDK 1.3 (if it's not, is version 2.1 compatible with version 1.3?) ?

**Comment by dotMorten** [comment]
It should be compatible just fine. I meant to ship an update last week that deprecates the backdrops in favor of the WinUI ones, but forgot my codesigning certificate expired, so just waiting for that to get renewed before pushing an update to nuget. But again it should be fine for you to upgrade. Just note that WinUI doesn't support declaring their backdrops in xaml 🙄

**Comment by Mysterious-Dev** [comment]
PR open for this issue #4660 ^^.

**Comment by dotMorten** [comment]
@Mysterious-dev Finally got my signing certificate updated, so WinUIEx v2.2 is out now
