### ISSUE TITLE
Remove all designer references from WinUI 3 / WASDK templates

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/TemplateStudio#4646]
All designer references should be removed from the WinUI 3 / WASDK templates.

* There are separate templates for UWP
* There is no designer for WinUI 3 / WASDK
* There are no plans to make a designer for WinUI 3 / WASDK

Ergo, the references are useless at best, and misleading + distracting at worst.

**Comment by mrlacey** [comment]
> There are separate templates for UWP

I'm not sure how this is relevant

> There is no designer for WinUI 3 / WASDK

yet....

> There are no plans to make a designer for WinUI 3 / WASDK

As publicly announced by Microsoft.
Plans of 3rd parties who are (or may) be working on such a designer should also be considered.

> Ergo, the references are useless at best, and misleading + distracting at worst.

I'd argue that there's currently limited value in their inclusion, but note that the `mc:Ignorable` attribute can be (& often is) used for more than to indicate that the `d` alias can be ignored. I find having it there in the templates to be useful

I understand the frustration that the lack of a designer can cause many people but I don't see any real benefit in making the change that is proposed here.
In the way that this proposal is worded, I think it is very unlikely to be accepted as doing so would indicate that Microsoft definitely will never create such a design tool and doesn't want to make it easy for anyone else to create such either.

**Comment by kmgallahan** [comment]
> I understand the frustration that the lack of a designer can cause many people

I'm not frustrated by the lack of a designer as I've never found them particularly useful.

I just created a project from the templates and saw all these references (which my code formatter removes as a cleanup step) and thought: why are these being added to WinUI files? It is comparable to inserting 3 using statements for unused namespaces at the top of all the C# files.

Your choice though.
