### ISSUE TITLE
Please update to Windows App SDK 1.3

### ISSUE THREAD

**Issue by manusoft** [microsoft/TemplateStudio#4656]
### Is your feature request related to a problem? Please describe.

More features available in new version, like
```cs
SystemBackdrop = new MicaBackdrop();
```
and more Window functions etc.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

**Comment by mikebattista** [comment]
MicaBackdrop is tracked by #4641. Do you have more specific requests?

The dependency has already been updated to 1.3 for the next release.

**Comment by manusoft** [comment]
@mikebattista Is the MainWindow is needed? in Uno platform there is no MainWindow.  And I have another question if I button on TitleBar, its showing but the click event is not working.

**Comment by AathifMahir** [comment]
> MicaBackdrop is tracked by #4641. Do you have more specific requests?
> 
> The dependency has already been updated to 1.3 for the next release.

Is there an ETA for Next Update for Template Studio with WinAppSDK 1.3?

**Comment by Mysterious-Dev** [comment]
I don't think. I will take a look tommorow to update the template with new System Backdrop API but I have some strange problems with WinUIEx (and I think, we will wait for an update of WinUIEx before) ^^.

**Comment by pratikone** [comment]
I am currently working to have  a small release with winappsdk 1.3. stay tuned :)

**Comment by pratikone** [comment]
this issue has been fixed by #4638 as well as #4666. Will be available in next release.
