### ISSUE TITLE
How to create a project with the help of a command in the Windows or VS console?

### ISSUE THREAD

**Issue by jhon65496** [microsoft/TemplateStudio#4677]
### Describe the solution you'd like

How to create a project with the help of a command in the Windows or VS console?
Example of logic:
 - The user opens the Windows or VS console;
 - Enters a command to select the folder where to place the project: `cd e:\TemplateStudioProjects\TemplateStudioApp01 \`
 - Enters a command with the template name and other template settings.
 - Result: in folder `e:\TemplateStudioProjects\TemplateStudioApp01\` a project is being created with the specified template settings.

### Additional context

Win-10

### Applies to the following platforms:

- [ ] WinUI
- [X] WPF
- [ ] UWP

**Comment by mrlacey** [comment]
Template Studio does not support being opened from a command or via the console.
It is a UI only tool.

Many of the features of Template Studio rely on custom functionality that is not part of the dotnet templating engine.
The configuration options are also, potentially, very complex and would be difficult to communicate and configure accurately with only command line options.

Additionally, much of the extended functionality relies on Visual Studio dependencies and so would not work without Visual Studio being available.

It was designed solely for use as a UI tool accessed from within Visual Studio. Changing this would be a large and complicated task that I cannot foresee happening. (Unless you--or someone else--wants to try.)
