### ISSUE TITLE
Visual Studio 2022 and Template Studio for WinUI (C#) hangs at creating project

### ISSUE THREAD

**Issue by riverar** [microsoft/TemplateStudio#4686]
### Describe the bug

After using the Template Studio for WinUI (C#) wizard, Visual Studio 2022 hangs at the creating project dialog.

### To Reproduce

1. Install Template Studio 5.4
2. Create a new project
  a. Project type: Navigation pane
  b. Design pattern: MVVM
  c. Pages: Add Settings
  d. Features: Add Self-Contained
4. Observe Creating project... dialog never closes

### Additional context

![image](https://github.com/microsoft/TemplateStudio/assets/475132/1e1580ba-8040-4223-bfaa-9d20ce3e25f3)

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

Windows 11 vNext (10.0.25375.1)
Visual Studio 2022 Enterprise (17.5.1)
Template Studio for WinUI 5.4

**Comment by riverar** [comment]
Thanks @mrlacey, that seems to workaround the issue indeed. Perhaps Template Studio should block this scenario until it's known working again?

**Comment by mrlacey** [comment]
> Thanks @mrlacey, that seems to workaround the issue indeed. Perhaps Template Studio should block this scenario until it's known working again?

Again?
It's never worked!

Could be a good look to test for this first 👍
