### ISSUE TITLE
WinUI3 Template Memory Leaking Problem from Template Studio for WinUI (C#)

### ISSUE THREAD

**Issue by Jack251970** [microsoft/TemplateStudio#4699]
### Describe the bug

I have encounter memory leak problem using WinUI3 template from extension "Template Studio for WinUI (C#)".
I try to change registering mode of all services from "AddAddTransient" to "AddScoped" to avoid building new services in unnecessary situations, but this problem still exists.
And if there is a page with the control "ListView", this problem with large memory leaking really annoys me. 

### To Reproduce

 1. Create a new project(New WinUI3 Desktop app) with extension "Template Studio for WinUI (C#)".
 2. Select a project type: "Navigation Pane".
 3. Add pages: "List Details" and "Settings".
 4. Add feature: "Self-Contained".
 5. Change registering mode of all services from "AddAddTransient" to "AddScoped" (e.g. change "services.AddAddTransient<SettingsViewModel>();" to "services.AddScoped<SettingsViewModel>();").
 6. Debug this project, and navigate between "ListDetailPage" and "SettingsPage", the "Process Memory" in "Diagnostic Tools" of Visual Studio will increase continuously.
 7. See memory leaking error.

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  17.6.4.
 - Template Studio Wizard Version: 5.4.
 - Windows Build: 19045.3155.

**Comment by mrlacey** [comment]
Is it leaking memory or is it just allocating more as you continually navigate forwards to new instances of pages?
As you add more pages to the navigation stack I'd expect it to use more memory.
If memory continues to go up once you navigate to a page, or memory isn't reclaimed after navigating back through the stack then it might indicate a leak.

**Comment by Jack251970** [comment]
So, the navigation stack is the "BackStack" of "Frame"? 
I edited the function "OnNavigated" in "NavigationService.cs"  to make sure in every navigation action, the "BackStack" of "Frame" will be cleaned which makes back button always diabled.
```
private void OnNavigated(object sender, NavigationEventArgs e)
    {
        if (sender is Frame frame)
        {
            /*var clearNavigation = (bool)frame.Tag;
            if (clearNavigation)
            {
                frame.BackStack.Clear();
            }*/

            // force to clean BackStack
            frame.BackStack.Clear();

            if (frame.GetPageViewModel() is INavigationAware navigationAware)
            {
                navigationAware.OnNavigatedTo(e.Parameter);
            }

            Navigated?.Invoke(sender, e);
        }
    }
```
And I make sure all viewmodels won't be created.
```
services.AddScoped<SettingsViewModel>();
services.AddScoped<SettingsPage>();
services.AddScoped<ListDetailsViewModel>();
services.AddScoped<ListDetailsPage>();
services.AddScoped<MainViewModel>();
services.AddScoped<MainPage>();
services.AddScoped<ShellPage>();
services.AddScoped<ShellViewModel>();
```
But the process memory still will increase continuously.

**Comment by Jack251970** [comment]
However, after adding break points to constructor functions, I found the constructor of one page will still be called when navigated to the page. But the constructor of the viewmodel is not. So, the navigation function is always creating new pages? How to avoid that?

**Comment by Jack251970** [comment]
In detail, when calling "var navigated = _frame.Navigate(pageType, parameter);" in "NavigateTo" function of "NavigationService.cs", it will always create new instance of pages. And I think it's the key to this problem.
I got started with .NET and WINUI3 shortly, but according to the knowledge of WPF, I thought that the navigation service should not create many instances of one page when navigation to the same page. 🧐

**Comment by mrlacey** [comment]
If you only want a single instance of a page, you probably want the Singleton scope. I can't find the docs link, but I believe that a "Scoped" resource is tied to the lifetime of the window within which it is created.

If you're deleting the pages from the navigation stack (which is what `Clear()` will do) then it will need to be recreated when you navigate to it again.

If you only want a single instance of a page, you should probably look at [Page.NavigationCacheMode](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.page.navigationcachemode?view=winrt-22621).

You also need to consider the user experience of only having a single instance of each page and how it is presented to users as they navigate the app. Depending on what your app does, it may or may not be expected that the same instance is shown each time they try and navigate to a "new" page.

**Comment by Jack251970** [comment]
Thank you for you detailed reply. Now I know this problem relate to the NavigationCacheMode of pages. I'm not very familiar with .Net development, and sorry for any inconvenience. 😥

**Comment by mrlacey** [comment]
> Thank you for you detailed reply. Now I know this problem relate to the NavigationCacheMode of pages. I'm not very familiar with .Net development, and sorry for any inconvenience. 

Not a problem. Don't be reluctant to ask questions. They help highlight things that aren't clear and ways documentation and sample code can be improved to help people with less experience.
