### ISSUE TITLE
Setting Dark mode from Settings Page makes the Minimize, Maximize, and Close buttons invisible.

### ISSUE THREAD

**Issue by Omenrevlis** [microsoft/TemplateStudio#4716]
### Describe the bug

In Navigation Template I added the settings. By default, it implements the ability to switch the app to Dark, Light, or Default. When I change it to Dark the Mininimize, Maximize, and Close buttons are still set to forground black and are invisible unless you hover over them.

I have not modified the toolbar from what the template created. 
I have not messed with setting any colors of anything. This is how it is after the template studio created it. 

### To Reproduce

 1. Create a Navigation based Template project
 2. Add a Settings page
 3. Make sure your computer is set to light mode
 4. Run the application
 5. Go to the settings page
 6. Change to Dark Mode (application only)

### Additional context

I see where the TitleBarHelper and the ShellPage CS sets the forcolor. Interestingly, if I put a breakpoint in either and run debug to the breakpoint, then just continue running, the title bar foreground is correct. 

So something is changing it back to light foreground settings, likely on another thread, but I'm not sure where.

When the main window is deactivated, you can see greyish buttons. But when the windows is active, they are the same color as  the title bar (black) and cannot be seen.  

![Light Mode](https://github.com/microsoft/TemplateStudio/assets/150300234/7994d311-20f1-4f1b-94ec-f938ee04794c)
![Not active window](https://github.com/microsoft/TemplateStudio/assets/150300234/4a400f0c-9445-4e20-9946-b0cc0c0e0615)
![Acitve window](https://github.com/microsoft/TemplateStudio/assets/150300234/8d5c23c3-b8bf-45f8-b096-9514c2dd1493)

### Applies to the following platforms:

- [X] WinUI
- [ ] WPF
- [ ] UWP

### About your setup

 - Visual Studio Version:  Version 17.8.0 Preview 7.0
 - Template Studio Wizard Version:  v5.4
  - Windows Build: Windows 11 Pro - 10.0.22621

**Comment by Mysterious-Dev** [comment]
If you use Windows App SDK 1.4, it's fixed with https://github.com/microsoft/TemplateStudio/commit/52d63a4538c676bf97e0486a0df5d44b2cd4841a. We just need to wait @pratikone for a binary release ^^.

**Comment by Jay-o-Way** [comment]
Looks like https://github.com/microsoft/microsoft-ui-xaml/issues/8899

**Comment by Jay-o-Way** [comment]
> if you to need the custom title bar in 1.4, you can move away from Window.ExtendsContentIntoTitleBar and use the new APIs under Window.AppWindow.TitleBar

https://github.com/microsoft/microsoft-ui-xaml/issues/8899#issuecomment-1742729923

What does the template do?

**Comment by Mysterious-Dev** [comment]
> Looks like https://github.com/microsoft/microsoft-ui-xaml/issues/8899
> @Mysterious-Dev where did you find the pr in MS repo that fixed it and for which exact version? I don't see any pr linkt to this ↑ issue.

It's a PR for TemplateStudio. I think he used TemplateStudio 5.4 and updated WindowsAppSDK to 1.4 (with new TitleBar customisation).

**Comment by Jay-o-Way** [comment]
I know. I asked what your source was. And what method does the template use.

**Comment by Omenrevlis** [comment]
I am using TemplateStudio 5.4 and WindowsAppSKD 1.4

**Comment by pratikone** [comment]
New release of Template Studio is here

**Comment by JoySurfer** [comment]
> New release of Template Studio is here. Do check if it is still happening.

It seems that these function calls in TitleBarHelper are no longer necessary.

//var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(App.MainWindow);
//if (hwnd == GetActiveWindow())
//{
// SendMessage(hwnd, WMACTIVATE, WAINACTIVE, IntPtr.Zero);
// SendMessage(hwnd, WMACTIVATE, WAACTIVE, IntPtr.Zero);
//}
//else
//{
// SendMessage(hwnd, WMACTIVATE, WAACTIVE, IntPtr.Zero);
// SendMessage(hwnd, WMACTIVATE, WAINACTIVE, IntPtr.Zero);
//}

**Comment by Omenrevlis** [comment]
> New release of Template Studio is here. Do check if it is still happening.

I updated to Template Studio 5.5 on the existing solution. There is some improvement but not fully fixed. 

If Windows is set to Dark Mode and App is set to default, it works.
If Windows is set to Dark Mode and App is set to Dark Mode, it works.
If Windows is set to Light Mode and App is set to Dark Mode, it does not work. They are hidden when window is Active. But visible when the window is inactive.

**Comment by Omenrevlis** [comment]
Starting a new Template Studio project to test and Good news, it works! So a new solution path is fine, but an upgrade to the Extension for Template Studio does not fix it. I can port all my stuff over to a new project. That's fine for me. 

However, I noticed what I think is a bug in 5.5. When creating a Template Studio solution, you can only name the project. The option to change the [solution](`url`) name is disabled. 
![Solution NamingDisabled](https://github.com/microsoft/TemplateStudio/assets/150300234/b471ae89-1286-48aa-a264-9f6d0da49094)

**Comment by Omenrevlis** [comment]
Well, I'm sorry but there is still some weirdness. Not with the pages themselves, but with ContentDialog. It tires to follow the OS for dark mode. 

If OS is light mode, and app is set to default all is great.
If OS is dark mode, and app is set to default all is great.
if OS is dark mode, and app is dark mode all is great.
**if OS is dark mode, and app is on light mode, the dialog is in dark mode.** 
**If OS is in light mode and app is in dark mode. the dialog is in light mode**

![image](https://github.com/microsoft/TemplateStudio/assets/150300234/fede0b66-e159-4f4f-badc-94bb500295de)
![image](https://github.com/microsoft/TemplateStudio/assets/150300234/1029dda1-23da-4f38-8135-bbbd763b4a5f)

**Comment by Omenrevlis** [comment]
Just for reference, the content of the dialog box is a Page object.

**Comment by Omenrevlis** [comment]
There is also a measly bug I think no one would care too much about. If the app is set to default and you have a dialog on screen from your app when the OS is changed to a dark or light mode, it only applies to the dialog and not the main window. This fixes itself when you close and restart the app, but it feels odd when it is happening.

**Comment by pratikone** [comment]
@Omenrevlis no bug is small. Do open an issue for that. 
Closing this one as it has been fixed.
