### ISSUE TITLE
How to have a template with extra localizable content

### ISSUE THREAD

**Issue by mrlacey** [microsoft/TemplateStudio#929]
I'm looking at adding features that will require extra UI content to be displayed in the wizard.
e.g. Asking for a custom value, rather than just a page name.

Doing this will require the template include text that is defined in the config file for display in the UI.
I'm happy that I can work out how to add the flexibility to the wizard to allow this but I'm not sure where the different translations of the text should be stored. Is there a way to include these in a translated tag within the localized version of template.json? Or will we require something new to handle this?

//cc @ralarcon @sibille

**Comment by mikebattista** [comment]
Closing out this stale issue. If it's still relevant, please reopen and provide more context on what features you are working on.
